#pragma once
#include "dbghelp_api.hpp"

////
// Autogenerated by script
////

extern "C" {
	__declspec(dllexport) BOOL __stdcall hook_EnumDirTree (
		HANDLE                hProcess,
		PCSTR                 RootPath,
		PCSTR                 InputPathName,
		PSTR                  OutputPathBuffer,
		PENUMDIRTREE_CALLBACK cb,
		PVOID                 data
	) {
		return real_dbghelp.EnumDirTree(hProcess, RootPath, InputPathName, OutputPathBuffer, cb, data);
	}
	__declspec(dllexport) BOOL __stdcall hook_EnumDirTreeW (
		HANDLE                 hProcess,
		PCWSTR                 RootPath,
		PCWSTR                 InputPathName,
		PWSTR                  OutputPathBuffer,
		PENUMDIRTREE_CALLBACKW cb,
		PVOID                  data
	) {
		return real_dbghelp.EnumDirTreeW(hProcess, RootPath, InputPathName, OutputPathBuffer, cb, data);
	}
	__declspec(dllexport) BOOL __stdcall hook_EnumerateLoadedModules (
		HANDLE                       hProcess,
		PENUMLOADED_MODULES_CALLBACK EnumLoadedModulesCallback,
		PVOID                        UserContext
	) {
		return real_dbghelp.EnumerateLoadedModules(hProcess, EnumLoadedModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_EnumerateLoadedModules64 (
		HANDLE                         hProcess,
		PENUMLOADED_MODULES_CALLBACK64 EnumLoadedModulesCallback,
		PVOID                          UserContext
	) {
		return real_dbghelp.EnumerateLoadedModules64(hProcess, EnumLoadedModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_EnumerateLoadedModulesEx (
		HANDLE                         hProcess,
		PENUMLOADED_MODULES_CALLBACK64 EnumLoadedModulesCallback,
		PVOID                          UserContext
	) {
		return real_dbghelp.EnumerateLoadedModulesEx(hProcess, EnumLoadedModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_EnumerateLoadedModulesExW (
		HANDLE                          hProcess,
		PENUMLOADED_MODULES_CALLBACKW64 EnumLoadedModulesCallback,
		PVOID                           UserContext
	) {
		return real_dbghelp.EnumerateLoadedModulesExW(hProcess, EnumLoadedModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_EnumerateLoadedModulesW64 (
		HANDLE                          hProcess,
		PENUMLOADED_MODULES_CALLBACKW64 EnumLoadedModulesCallback,
		PVOID                           UserContext
	) {
		return real_dbghelp.EnumerateLoadedModulesW64(hProcess, EnumLoadedModulesCallback, UserContext);
	}
	__declspec(dllexport) HANDLE __stdcall hook_FindDebugInfoFile (
		PCSTR FileName,
		PCSTR SymbolPath,
		PSTR  DebugFilePath
	) {
		return real_dbghelp.FindDebugInfoFile(FileName, SymbolPath, DebugFilePath);
	}
	__declspec(dllexport) HANDLE __stdcall hook_FindDebugInfoFileEx (
		PCSTR                     FileName,
		PCSTR                     SymbolPath,
		PSTR                      DebugFilePath,
		PFIND_DEBUG_FILE_CALLBACK Callback,
		PVOID                     CallerData
	) {
		return real_dbghelp.FindDebugInfoFileEx(FileName, SymbolPath, DebugFilePath, Callback, CallerData);
	}
	__declspec(dllexport) HANDLE __stdcall hook_FindDebugInfoFileExW (
		PCWSTR                     FileName,
		PCWSTR                     SymbolPath,
		PWSTR                      DebugFilePath,
		PFIND_DEBUG_FILE_CALLBACKW Callback,
		PVOID                      CallerData
	) {
		return real_dbghelp.FindDebugInfoFileExW(FileName, SymbolPath, DebugFilePath, Callback, CallerData);
	}
	__declspec(dllexport) HANDLE __stdcall hook_FindExecutableImage (
		PCSTR FileName,
		PCSTR SymbolPath,
		PSTR  ImageFilePath
	) {
		return real_dbghelp.FindExecutableImage(FileName, SymbolPath, ImageFilePath);
	}
	__declspec(dllexport) HANDLE __stdcall hook_FindExecutableImageEx (
		PCSTR                   FileName,
		PCSTR                   SymbolPath,
		PSTR                    ImageFilePath,
		PFIND_EXE_FILE_CALLBACK Callback,
		PVOID                   CallerData
	) {
		return real_dbghelp.FindExecutableImageEx(FileName, SymbolPath, ImageFilePath, Callback, CallerData);
	}
	__declspec(dllexport) HANDLE __stdcall hook_FindExecutableImageExW (
		PCWSTR                   FileName,
		PCWSTR                   SymbolPath,
		PWSTR                    ImageFilePath,
		PFIND_EXE_FILE_CALLBACKW Callback,
		PVOID                    CallerData
	) {
		return real_dbghelp.FindExecutableImageExW(FileName, SymbolPath, ImageFilePath, Callback, CallerData);
	}
	__declspec(dllexport) DWORD __stdcall hook_GetSymLoadError () {
		return real_dbghelp.GetSymLoadError();
	}
	__declspec(dllexport) DWORD __stdcall hook_GetTimestampForLoadedLibrary (
		HMODULE Module
	) {
		return real_dbghelp.GetTimestampForLoadedLibrary(Module);
	}
	__declspec(dllexport) PVOID __stdcall hook_ImageDirectoryEntryToData (
		PVOID   Base,
		BOOLEAN MappedAsImage,
		USHORT  DirectoryEntry,
		PULONG  Size
	) {
		return real_dbghelp.ImageDirectoryEntryToData(Base, MappedAsImage, DirectoryEntry, Size);
	}
	__declspec(dllexport) PVOID __stdcall hook_ImageDirectoryEntryToDataEx (
		PVOID                 Base,
		BOOLEAN               MappedAsImage,
		USHORT                DirectoryEntry,
		PULONG                Size,
		PIMAGE_SECTION_HEADER* FoundHeader
	) {
		return real_dbghelp.ImageDirectoryEntryToDataEx(Base, MappedAsImage, DirectoryEntry, Size, FoundHeader);
	}
	__declspec(dllexport) PIMAGE_NT_HEADERS __stdcall hook_ImageNtHeader (
		PVOID Base
	) {
		return real_dbghelp.ImageNtHeader(Base);
	}
	__declspec(dllexport) PIMAGE_SECTION_HEADER __stdcall hook_ImageRvaToSection (
		PIMAGE_NT_HEADERS NtHeaders,
		PVOID             Base,
		ULONG             Rva
	) {
		return real_dbghelp.ImageRvaToSection(NtHeaders, Base, Rva);
	}
	__declspec(dllexport) PVOID __stdcall hook_ImageRvaToVa (
		PIMAGE_NT_HEADERS     NtHeaders,
		PVOID                 Base,
		ULONG                 Rva,
		PIMAGE_SECTION_HEADER* LastRvaSection
	) {
		return real_dbghelp.ImageRvaToVa(NtHeaders, Base, Rva, LastRvaSection);
	}
	__declspec(dllexport) LPAPI_VERSION __stdcall hook_ImagehlpApiVersion () {
		return real_dbghelp.ImagehlpApiVersion();
	}
	__declspec(dllexport) LPAPI_VERSION __stdcall hook_ImagehlpApiVersionEx (
		LPAPI_VERSION AppVersion
	) {
		return real_dbghelp.ImagehlpApiVersionEx(AppVersion);
	}
	__declspec(dllexport) BOOL __stdcall hook_MakeSureDirectoryPathExists (
		PCSTR DirPath
	) {
		return real_dbghelp.MakeSureDirectoryPathExists(DirPath);
	}
	__declspec(dllexport) BOOL __stdcall hook_MiniDumpReadDumpStream (
		PVOID               BaseOfDump,
		ULONG               StreamNumber,
		PMINIDUMP_DIRECTORY* Dir,
		PVOID* StreamPointer,
		ULONG* StreamSize
	) {
		return real_dbghelp.MiniDumpReadDumpStream(BaseOfDump, StreamNumber, Dir, StreamPointer, StreamSize);
	}
	__declspec(dllexport) BOOL __stdcall hook_MiniDumpWriteDump (
		HANDLE                            hProcess,
		DWORD                             ProcessId,
		HANDLE                            hFile,
		MINIDUMP_TYPE                     DumpType,
		PMINIDUMP_EXCEPTION_INFORMATION   ExceptionParam,
		PMINIDUMP_USER_STREAM_INFORMATION UserStreamParam,
		PMINIDUMP_CALLBACK_INFORMATION    CallbackParam
	) {
		return real_dbghelp.MiniDumpWriteDump(hProcess, ProcessId, hFile, DumpType, ExceptionParam, UserStreamParam, CallbackParam);
	}
	__declspec(dllexport) BOOL __stdcall hook_SearchTreeForFile (
		PCSTR RootPath,
		PCSTR InputPathName,
		PSTR  OutputPathBuffer
	) {
		return real_dbghelp.SearchTreeForFile(RootPath, InputPathName, OutputPathBuffer);
	}
	__declspec(dllexport) BOOL __stdcall hook_SearchTreeForFileW (
		PCWSTR RootPath,
		PCWSTR InputPathName,
		PWSTR  OutputPathBuffer
	) {
		return real_dbghelp.SearchTreeForFileW(RootPath, InputPathName, OutputPathBuffer);
	}
	__declspec(dllexport) void __stdcall hook_SetSymLoadError (
		DWORD error
	) {
		return real_dbghelp.SetSymLoadError(error);
	}
	__declspec(dllexport) BOOL __stdcall hook_StackWalk (
		DWORD                          MachineType,
		HANDLE                         hProcess,
		HANDLE                         hThread,
		LPSTACKFRAME                   StackFrame,
		PVOID                          ContextRecord,
		PREAD_PROCESS_MEMORY_ROUTINE   ReadMemoryRoutine,
		PFUNCTION_TABLE_ACCESS_ROUTINE FunctionTableAccessRoutine,
		PGET_MODULE_BASE_ROUTINE       GetModuleBaseRoutine,
		PTRANSLATE_ADDRESS_ROUTINE     TranslateAddress
	) {
		return real_dbghelp.StackWalk(MachineType, hProcess, hThread, StackFrame, ContextRecord, ReadMemoryRoutine, FunctionTableAccessRoutine, GetModuleBaseRoutine, TranslateAddress);
	}
	__declspec(dllexport) BOOL __stdcall hook_StackWalk64 (
		DWORD                            MachineType,
		HANDLE                           hProcess,
		HANDLE                           hThread,
		LPSTACKFRAME64                   StackFrame,
		PVOID                            ContextRecord,
		PREAD_PROCESS_MEMORY_ROUTINE64   ReadMemoryRoutine,
		PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine,
		PGET_MODULE_BASE_ROUTINE64       GetModuleBaseRoutine,
		PTRANSLATE_ADDRESS_ROUTINE64     TranslateAddress
	) {
		return real_dbghelp.StackWalk64(MachineType, hProcess, hThread, StackFrame, ContextRecord, ReadMemoryRoutine, FunctionTableAccessRoutine, GetModuleBaseRoutine, TranslateAddress);
	}
	__declspec(dllexport) BOOL __stdcall hook_StackWalkEx (
		DWORD                            MachineType,
		HANDLE                           hProcess,
		HANDLE                           hThread,
		LPSTACKFRAME_EX                  StackFrame,
		PVOID                            ContextRecord,
		PREAD_PROCESS_MEMORY_ROUTINE64   ReadMemoryRoutine,
		PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine,
		PGET_MODULE_BASE_ROUTINE64       GetModuleBaseRoutine,
		PTRANSLATE_ADDRESS_ROUTINE64     TranslateAddress,
		DWORD                            Flags
	) {
		return real_dbghelp.StackWalkEx(MachineType, hProcess, hThread, StackFrame, ContextRecord, ReadMemoryRoutine, FunctionTableAccessRoutine, GetModuleBaseRoutine, TranslateAddress, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymAddSourceStream (
		HANDLE  hProcess,
		ULONG64 Base,
		PCSTR   StreamFile,
		PBYTE   Buffer,
		size_t  Size
	) {
		return real_dbghelp.SymAddSourceStream(hProcess, Base, StreamFile, Buffer, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymAddSourceStreamA (
		HANDLE  hProcess,
		ULONG64 Base,
		PCSTR   StreamFile,
		PBYTE   Buffer,
		size_t  Size
	) {
		return real_dbghelp.SymAddSourceStreamA(hProcess, Base, StreamFile, Buffer, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymAddSourceStreamW (
		HANDLE  hProcess,
		ULONG64 Base,
		PCWSTR  FileSpec,
		PBYTE   Buffer,
		size_t  Size
	) {
		return real_dbghelp.SymAddSourceStreamW(hProcess, Base, FileSpec, Buffer, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymAddSymbol (
		HANDLE  hProcess,
		ULONG64 BaseOfDll,
		PCSTR   Name,
		DWORD64 Address,
		DWORD   Size,
		DWORD   Flags
	) {
		return real_dbghelp.SymAddSymbol(hProcess, BaseOfDll, Name, Address, Size, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymAddSymbolW (
		HANDLE  hProcess,
		ULONG64 BaseOfDll,
		PCWSTR  Name,
		DWORD64 Address,
		DWORD   Size,
		DWORD   Flags
	) {
		return real_dbghelp.SymAddSymbolW(hProcess, BaseOfDll, Name, Address, Size, Flags);
	}
	__declspec(dllexport) DWORD __stdcall hook_SymCompareInlineTrace (
		HANDLE  hProcess,
		DWORD64 Address1,
		DWORD   InlineContext1,
		DWORD64 RetAddress1,
		DWORD64 Address2,
		DWORD64 RetAddress2
	) {
		return real_dbghelp.SymCompareInlineTrace(hProcess, Address1, InlineContext1, RetAddress1, Address2, RetAddress2);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymDeleteSymbol (
		HANDLE  hProcess,
		ULONG64 BaseOfDll,
		PCSTR   Name,
		DWORD64 Address,
		DWORD   Flags
	) {
		return real_dbghelp.SymDeleteSymbol(hProcess, BaseOfDll, Name, Address, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymDeleteSymbolW (
		HANDLE  hProcess,
		ULONG64 BaseOfDll,
		PCWSTR  Name,
		DWORD64 Address,
		DWORD   Flags
	) {
		return real_dbghelp.SymDeleteSymbolW(hProcess, BaseOfDll, Name, Address, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumLines (
		HANDLE                  hProcess,
		ULONG64                 Base,
		PCSTR                   Obj,
		PCSTR                   File,
		PSYM_ENUMLINES_CALLBACK EnumLinesCallback,
		PVOID                   UserContext
	) {
		return real_dbghelp.SymEnumLines(hProcess, Base, Obj, File, EnumLinesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumLinesW (
		HANDLE                   hProcess,
		ULONG64                  Base,
		PCWSTR                   Obj,
		PCWSTR                   File,
		PSYM_ENUMLINES_CALLBACKW EnumLinesCallback,
		PVOID                    UserContext
	) {
		return real_dbghelp.SymEnumLinesW(hProcess, Base, Obj, File, EnumLinesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumProcesses (
		PSYM_ENUMPROCESSES_CALLBACK EnumProcessesCallback,
		PVOID                       UserContext
	) {
		return real_dbghelp.SymEnumProcesses(EnumProcessesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSourceFileTokens (
		HANDLE                        hProcess,
		ULONG64                       Base,
		PENUMSOURCEFILETOKENSCALLBACK Callback
	) {
		return real_dbghelp.SymEnumSourceFileTokens(hProcess, Base, Callback);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSourceFiles (
		HANDLE                        hProcess,
		ULONG64                       ModBase,
		PCSTR                         Mask,
		PSYM_ENUMSOURCEFILES_CALLBACK cbSrcFiles,
		PVOID                         UserContext
	) {
		return real_dbghelp.SymEnumSourceFiles(hProcess, ModBase, Mask, cbSrcFiles, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSourceFilesW (
		HANDLE                         hProcess,
		ULONG64                        ModBase,
		PCWSTR                         Mask,
		PSYM_ENUMSOURCEFILES_CALLBACKW cbSrcFiles,
		PVOID                          UserContext
	) {
		return real_dbghelp.SymEnumSourceFilesW(hProcess, ModBase, Mask, cbSrcFiles, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSourceLines (
		HANDLE                  hProcess,
		ULONG64                 Base,
		PCSTR                   Obj,
		PCSTR                   File,
		DWORD                   Line,
		DWORD                   Flags,
		PSYM_ENUMLINES_CALLBACK EnumLinesCallback,
		PVOID                   UserContext
	) {
		return real_dbghelp.SymEnumSourceLines(hProcess, Base, Obj, File, Line, Flags, EnumLinesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSourceLinesW (
		HANDLE                   hProcess,
		ULONG64                  Base,
		PCWSTR                   Obj,
		PCWSTR                   File,
		DWORD                    Line,
		DWORD                    Flags,
		PSYM_ENUMLINES_CALLBACKW EnumLinesCallback,
		PVOID                    UserContext
	) {
		return real_dbghelp.SymEnumSourceLinesW(hProcess, Base, Obj, File, Line, Flags, EnumLinesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSymbols (
		HANDLE                         hProcess,
		ULONG64                        BaseOfDll,
		PCSTR                          Mask,
		PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                          UserContext
	) {
		return real_dbghelp.SymEnumSymbols(hProcess, BaseOfDll, Mask, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSymbolsEx (
		HANDLE                         hProcess,
		ULONG64                        BaseOfDll,
		PCSTR                          Mask,
		PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                          UserContext,
		DWORD                          Options
	) {
		return real_dbghelp.SymEnumSymbolsEx(hProcess, BaseOfDll, Mask, EnumSymbolsCallback, UserContext, Options);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSymbolsExW (
		HANDLE                          hProcess,
		ULONG64                         BaseOfDll,
		PCWSTR                          Mask,
		PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                           UserContext,
		DWORD                           Options
	) {
		return real_dbghelp.SymEnumSymbolsExW(hProcess, BaseOfDll, Mask, EnumSymbolsCallback, UserContext, Options);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSymbolsForAddr (
		HANDLE                         hProcess,
		DWORD64                        Address,
		PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                          UserContext
	) {
		return real_dbghelp.SymEnumSymbolsForAddr(hProcess, Address, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSymbolsForAddrW (
		HANDLE                          hProcess,
		DWORD64                         Address,
		PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                           UserContext
	) {
		return real_dbghelp.SymEnumSymbolsForAddrW(hProcess, Address, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumSymbolsW (
		HANDLE                          hProcess,
		ULONG64                         BaseOfDll,
		PCWSTR                          Mask,
		PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                           UserContext
	) {
		return real_dbghelp.SymEnumSymbolsW(hProcess, BaseOfDll, Mask, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumTypes (
		HANDLE                         hProcess,
		ULONG64                        BaseOfDll,
		PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                          UserContext
	) {
		return real_dbghelp.SymEnumTypes(hProcess, BaseOfDll, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumTypesByName (
		HANDLE                         hProcess,
		ULONG64                        BaseOfDll,
		PCSTR                          mask,
		PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                          UserContext
	) {
		return real_dbghelp.SymEnumTypesByName(hProcess, BaseOfDll, mask, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumTypesByNameW (
		HANDLE                          hProcess,
		ULONG64                         BaseOfDll,
		PCWSTR                          mask,
		PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                           UserContext
	) {
		return real_dbghelp.SymEnumTypesByNameW(hProcess, BaseOfDll, mask, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumTypesW (
		HANDLE                          hProcess,
		ULONG64                         BaseOfDll,
		PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                           UserContext
	) {
		return real_dbghelp.SymEnumTypesW(hProcess, BaseOfDll, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateModules (
		HANDLE                    hProcess,
		PSYM_ENUMMODULES_CALLBACK EnumModulesCallback,
		PVOID                     UserContext
	) {
		return real_dbghelp.SymEnumerateModules(hProcess, EnumModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateModules64 (
		HANDLE                      hProcess,
		PSYM_ENUMMODULES_CALLBACK64 EnumModulesCallback,
		PVOID                       UserContext
	) {
		return real_dbghelp.SymEnumerateModules64(hProcess, EnumModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateModulesW64 (
		HANDLE                       hProcess,
		PSYM_ENUMMODULES_CALLBACKW64 EnumModulesCallback,
		PVOID                        UserContext
	) {
		return real_dbghelp.SymEnumerateModulesW64(hProcess, EnumModulesCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateSymbols (
		HANDLE                    hProcess,
		ULONG                     BaseOfDll,
		PSYM_ENUMSYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                     UserContext
	) {
		return real_dbghelp.SymEnumerateSymbols(hProcess, BaseOfDll, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateSymbols64 (
		HANDLE                      hProcess,
		ULONG64                     BaseOfDll,
		PSYM_ENUMSYMBOLS_CALLBACK64 EnumSymbolsCallback,
		PVOID                       UserContext
	) {
		return real_dbghelp.SymEnumerateSymbols64(hProcess, BaseOfDll, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateSymbolsW (
		HANDLE                     hProcess,
		ULONG                      BaseOfDll,
		PSYM_ENUMSYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                      UserContext
	) {
		return real_dbghelp.SymEnumerateSymbolsW(hProcess, BaseOfDll, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymEnumerateSymbolsW64 (
		HANDLE                       hProcess,
		ULONG64                      BaseOfDll,
		PSYM_ENUMSYMBOLS_CALLBACK64W EnumSymbolsCallback,
		PVOID                        UserContext
	) {
		return real_dbghelp.SymEnumerateSymbolsW64(hProcess, BaseOfDll, EnumSymbolsCallback, UserContext);
	}
	__declspec(dllexport) HANDLE __stdcall hook_SymFindDebugInfoFile (
		HANDLE                    hProcess,
		PCSTR                     FileName,
		PSTR                      DebugFilePath,
		PFIND_DEBUG_FILE_CALLBACK Callback,
		PVOID                     CallerData
	) {
		return real_dbghelp.SymFindDebugInfoFile(hProcess, FileName, DebugFilePath, Callback, CallerData);
	}
	__declspec(dllexport) HANDLE __stdcall hook_SymFindDebugInfoFileW (
		HANDLE                     hProcess,
		PCWSTR                     FileName,
		PWSTR                      DebugFilePath,
		PFIND_DEBUG_FILE_CALLBACKW Callback,
		PVOID                      CallerData
	) {
		return real_dbghelp.SymFindDebugInfoFileW(hProcess, FileName, DebugFilePath, Callback, CallerData);
	}
	__declspec(dllexport) HANDLE __stdcall hook_SymFindExecutableImage (
		HANDLE                  hProcess,
		PCSTR                   FileName,
		PSTR                    ImageFilePath,
		PFIND_EXE_FILE_CALLBACK Callback,
		PVOID                   CallerData
	) {
		return real_dbghelp.SymFindExecutableImage(hProcess, FileName, ImageFilePath, Callback, CallerData);
	}
	__declspec(dllexport) HANDLE __stdcall hook_SymFindExecutableImageW (
		HANDLE                   hProcess,
		PCWSTR                   FileName,
		PWSTR                    ImageFilePath,
		PFIND_EXE_FILE_CALLBACKW Callback,
		PVOID                    CallerData
	) {
		return real_dbghelp.SymFindExecutableImageW(hProcess, FileName, ImageFilePath, Callback, CallerData);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFindFileInPath (
		HANDLE                  hprocess,
		PCSTR                   SearchPath,
		PCSTR                   FileName,
		PVOID                   id,
		DWORD                   two,
		DWORD                   three,
		DWORD                   flags,
		PSTR                    FoundFile,
		PFINDFILEINPATHCALLBACK callback,
		PVOID                   context
	) {
		return real_dbghelp.SymFindFileInPath(hprocess, SearchPath, FileName, id, two, three, flags, FoundFile, callback, context);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFindFileInPathW (
		HANDLE                   hprocess,
		PCWSTR                   SearchPath,
		PCWSTR                   FileName,
		PVOID                    id,
		DWORD                    two,
		DWORD                    three,
		DWORD                    flags,
		PWSTR                    FoundFile,
		PFINDFILEINPATHCALLBACKW callback,
		PVOID                    context
	) {
		return real_dbghelp.SymFindFileInPathW(hprocess, SearchPath, FileName, id, two, three, flags, FoundFile, callback, context);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFromIndex (
		HANDLE       hProcess,
		ULONG64      BaseOfDll,
		DWORD        Index,
		PSYMBOL_INFO Symbol
	) {
		return real_dbghelp.SymFromIndex(hProcess, BaseOfDll, Index, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFromIndexW (
		HANDLE        hProcess,
		ULONG64       BaseOfDll,
		DWORD         Index,
		PSYMBOL_INFOW Symbol
	) {
		return real_dbghelp.SymFromIndexW(hProcess, BaseOfDll, Index, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFromName (
		HANDLE       hProcess,
		PCSTR        Name,
		PSYMBOL_INFO Symbol
	) {
		return real_dbghelp.SymFromName(hProcess, Name, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFromNameW (
		HANDLE        hProcess,
		PCWSTR        Name,
		PSYMBOL_INFOW Symbol
	) {
		return real_dbghelp.SymFromNameW(hProcess, Name, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFromToken (
		HANDLE       hProcess,
		DWORD64      Base,
		DWORD        Token,
		PSYMBOL_INFO Symbol
	) {
		return real_dbghelp.SymFromToken(hProcess, Base, Token, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymFromTokenW (
		HANDLE        hProcess,
		DWORD64       Base,
		DWORD         Token,
		PSYMBOL_INFOW Symbol
	) {
		return real_dbghelp.SymFromTokenW(hProcess, Base, Token, Symbol);
	}
	__declspec(dllexport) PVOID __stdcall hook_SymFunctionTableAccess (
		HANDLE hProcess,
		DWORD  AddrBase
	) {
		return real_dbghelp.SymFunctionTableAccess(hProcess, AddrBase);
	}
	__declspec(dllexport) PVOID __stdcall hook_SymFunctionTableAccess64 (
		HANDLE  hProcess,
		DWORD64 AddrBase
	) {
		return real_dbghelp.SymFunctionTableAccess64(hProcess, AddrBase);
	}
	__declspec(dllexport) PVOID __stdcall hook_SymFunctionTableAccess64AccessRoutines (
		HANDLE                         hProcess,
		DWORD64                        AddrBase,
		PREAD_PROCESS_MEMORY_ROUTINE64 ReadMemoryRoutine,
		PGET_MODULE_BASE_ROUTINE64     GetModuleBaseRoutine
	) {
		return real_dbghelp.SymFunctionTableAccess64AccessRoutines(hProcess, AddrBase, ReadMemoryRoutine, GetModuleBaseRoutine);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetExtendedOption (
		IMAGEHLP_EXTENDED_OPTIONS option
	) {
		return real_dbghelp.SymGetExtendedOption(option);
	}
	__declspec(dllexport) ULONG __stdcall hook_SymGetFileLineOffsets64 (
		HANDLE   hProcess,
		PCSTR    ModuleName,
		PCSTR    FileName,
		PDWORD64 Buffer,
		ULONG    BufferLines
	) {
		return real_dbghelp.SymGetFileLineOffsets64(hProcess, ModuleName, FileName, Buffer, BufferLines);
	}
	__declspec(dllexport) PCHAR __stdcall hook_SymGetHomeDirectory (
		DWORD  type,
		PSTR   dir,
		size_t size
	) {
		return real_dbghelp.SymGetHomeDirectory(type, dir, size);
	}
	__declspec(dllexport) PWSTR __stdcall hook_SymGetHomeDirectoryW (
		DWORD  type,
		PWSTR  dir,
		size_t size
	) {
		return real_dbghelp.SymGetHomeDirectoryW(type, dir, size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineFromAddr (
		HANDLE         hProcess,
		DWORD          dwAddr,
		PDWORD         pdwDisplacement,
		PIMAGEHLP_LINE Line
	) {
		return real_dbghelp.SymGetLineFromAddr(hProcess, dwAddr, pdwDisplacement, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineFromName (
		HANDLE         hProcess,
		PCSTR          ModuleName,
		PCSTR          FileName,
		DWORD          dwLineNumber,
		PLONG          plDisplacement,
		PIMAGEHLP_LINE Line
	) {
		return real_dbghelp.SymGetLineFromName(hProcess, ModuleName, FileName, dwLineNumber, plDisplacement, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineFromName64 (
		HANDLE           hProcess,
		PCSTR            ModuleName,
		PCSTR            FileName,
		DWORD            dwLineNumber,
		PLONG            plDisplacement,
		PIMAGEHLP_LINE64 Line
	) {
		return real_dbghelp.SymGetLineFromName64(hProcess, ModuleName, FileName, dwLineNumber, plDisplacement, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineFromNameW64 (
		HANDLE            hProcess,
		PCWSTR            ModuleName,
		PCWSTR            FileName,
		DWORD             dwLineNumber,
		PLONG             plDisplacement,
		PIMAGEHLP_LINEW64 Line
	) {
		return real_dbghelp.SymGetLineFromNameW64(hProcess, ModuleName, FileName, dwLineNumber, plDisplacement, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineNext (
		HANDLE         hProcess,
		PIMAGEHLP_LINE Line
	) {
		return real_dbghelp.SymGetLineNext(hProcess, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineNext64 (
		HANDLE           hProcess,
		PIMAGEHLP_LINE64 Line
	) {
		return real_dbghelp.SymGetLineNext64(hProcess, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLineNextW64 (
		HANDLE            hProcess,
		PIMAGEHLP_LINEW64 Line
	) {
		return real_dbghelp.SymGetLineNextW64(hProcess, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLinePrev (
		HANDLE         hProcess,
		PIMAGEHLP_LINE Line
	) {
		return real_dbghelp.SymGetLinePrev(hProcess, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLinePrev64 (
		HANDLE           hProcess,
		PIMAGEHLP_LINE64 Line
	) {
		return real_dbghelp.SymGetLinePrev64(hProcess, Line);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetLinePrevW64 (
		HANDLE            hProcess,
		PIMAGEHLP_LINEW64 Line
	) {
		return real_dbghelp.SymGetLinePrevW64(hProcess, Line);
	}
	__declspec(dllexport) DWORD __stdcall hook_SymGetModuleBase (
		HANDLE hProcess,
		DWORD  dwAddr
	) {
		return real_dbghelp.SymGetModuleBase(hProcess, dwAddr);
	}
	__declspec(dllexport) DWORD64 __stdcall hook_SymGetModuleBase64 (
		HANDLE  hProcess,
		DWORD64 qwAddr
	) {
		return real_dbghelp.SymGetModuleBase64(hProcess, qwAddr);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetModuleInfo (
		HANDLE           hProcess,
		DWORD            dwAddr,
		PIMAGEHLP_MODULE ModuleInfo
	) {
		return real_dbghelp.SymGetModuleInfo(hProcess, dwAddr, ModuleInfo);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetModuleInfo64 (
		HANDLE             hProcess,
		DWORD64            qwAddr,
		PIMAGEHLP_MODULE64 ModuleInfo
	) {
		return real_dbghelp.SymGetModuleInfo64(hProcess, qwAddr, ModuleInfo);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetModuleInfoW (
		HANDLE            hProcess,
		DWORD             dwAddr,
		PIMAGEHLP_MODULEW ModuleInfo
	) {
		return real_dbghelp.SymGetModuleInfoW(hProcess, dwAddr, ModuleInfo);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetModuleInfoW64 (
		HANDLE              hProcess,
		DWORD64             qwAddr,
		PIMAGEHLP_MODULEW64 ModuleInfo
	) {
		return real_dbghelp.SymGetModuleInfoW64(hProcess, qwAddr, ModuleInfo);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetOmaps (
		HANDLE   hProcess,
		DWORD64  BaseOfDll,
		POMAP* OmapTo,
		PDWORD64 cOmapTo,
		POMAP* OmapFrom,
		PDWORD64 cOmapFrom
	) {
		return real_dbghelp.SymGetOmaps(hProcess, BaseOfDll, OmapTo, cOmapTo, OmapFrom, cOmapFrom);
	}
	__declspec(dllexport) DWORD __stdcall hook_SymGetOptions () {
		return real_dbghelp.SymGetOptions();
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetScope (
		HANDLE       hProcess,
		ULONG64      BaseOfDll,
		DWORD        Index,
		PSYMBOL_INFO Symbol
	) {
		return real_dbghelp.SymGetScope(hProcess, BaseOfDll, Index, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetScopeW (
		HANDLE        hProcess,
		ULONG64       BaseOfDll,
		DWORD         Index,
		PSYMBOL_INFOW Symbol
	) {
		return real_dbghelp.SymGetScopeW(hProcess, BaseOfDll, Index, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSearchPath (
		HANDLE hProcess,
		PSTR   SearchPath,
		DWORD  SearchPathLength
	) {
		return real_dbghelp.SymGetSearchPath(hProcess, SearchPath, SearchPathLength);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSearchPathW (
		HANDLE hProcess,
		PWSTR  SearchPath,
		DWORD  SearchPathLength
	) {
		return real_dbghelp.SymGetSearchPathW(hProcess, SearchPath, SearchPathLength);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFile (
		HANDLE  hProcess,
		ULONG64 Base,
		PCSTR   Params,
		PCSTR   FileSpec,
		PSTR    FilePath,
		DWORD   Size
	) {
		return real_dbghelp.SymGetSourceFile(hProcess, Base, Params, FileSpec, FilePath, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileChecksum (
		HANDLE  hProcess,
		ULONG64 Base,
		PCSTR   FileSpec,
		DWORD* pCheckSumType,
		BYTE* pChecksum,
		DWORD   checksumSize,
		DWORD* pActualBytesWritten
	) {
		return real_dbghelp.SymGetSourceFileChecksum(hProcess, Base, FileSpec, pCheckSumType, pChecksum, checksumSize, pActualBytesWritten);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileChecksumW (
		HANDLE  hProcess,
		ULONG64 Base,
		PCWSTR  FileSpec,
		DWORD* pCheckSumType,
		BYTE* pChecksum,
		DWORD   checksumSize,
		DWORD* pActualBytesWritten
	) {
		return real_dbghelp.SymGetSourceFileChecksumW(hProcess, Base, FileSpec, pCheckSumType, pChecksum, checksumSize, pActualBytesWritten);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileFromToken (
		HANDLE hProcess,
		PVOID  Token,
		PCSTR  Params,
		PSTR   FilePath,
		DWORD  Size
	) {
		return real_dbghelp.SymGetSourceFileFromToken(hProcess, Token, Params, FilePath, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileFromTokenW (
		HANDLE hProcess,
		PVOID  Token,
		PCWSTR Params,
		PWSTR  FilePath,
		DWORD  Size
	) {
		return real_dbghelp.SymGetSourceFileFromTokenW(hProcess, Token, Params, FilePath, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileToken (
		HANDLE  hProcess,
		ULONG64 Base,
		PCSTR   FileSpec,
		PVOID* Token,
		DWORD* Size
	) {
		return real_dbghelp.SymGetSourceFileToken(hProcess, Base, FileSpec, Token, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileTokenW (
		HANDLE  hProcess,
		ULONG64 Base,
		PCWSTR  FileSpec,
		PVOID* Token,
		DWORD* Size
	) {
		return real_dbghelp.SymGetSourceFileTokenW(hProcess, Base, FileSpec, Token, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceFileW (
		HANDLE  hProcess,
		ULONG64 Base,
		PCWSTR  Params,
		PCWSTR  FileSpec,
		PWSTR   FilePath,
		DWORD   Size
	) {
		return real_dbghelp.SymGetSourceFileW(hProcess, Base, Params, FileSpec, FilePath, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceVarFromToken (
		HANDLE hProcess,
		PVOID  Token,
		PCSTR  Params,
		PCSTR  VarName,
		PSTR   Value,
		DWORD  Size
	) {
		return real_dbghelp.SymGetSourceVarFromToken(hProcess, Token, Params, VarName, Value, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSourceVarFromTokenW (
		HANDLE hProcess,
		PVOID  Token,
		PCWSTR Params,
		PCWSTR VarName,
		PWSTR  Value,
		DWORD  Size
	) {
		return real_dbghelp.SymGetSourceVarFromTokenW(hProcess, Token, Params, VarName, Value, Size);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymFromAddr (
		HANDLE           hProcess,
		DWORD            dwAddr,
		PDWORD           pdwDisplacement,
		PIMAGEHLP_SYMBOL Symbol
	) {
		return real_dbghelp.SymGetSymFromAddr(hProcess, dwAddr, pdwDisplacement, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymFromAddr64 (
		HANDLE             hProcess,
		DWORD64            qwAddr,
		PDWORD64           pdwDisplacement,
		PIMAGEHLP_SYMBOL64 Symbol
	) {
		return real_dbghelp.SymGetSymFromAddr64(hProcess, qwAddr, pdwDisplacement, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymFromName (
		HANDLE           hProcess,
		PCSTR            Name,
		PIMAGEHLP_SYMBOL Symbol
	) {
		return real_dbghelp.SymGetSymFromName(hProcess, Name, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymFromName64 (
		HANDLE             hProcess,
		PCSTR              Name,
		PIMAGEHLP_SYMBOL64 Symbol
	) {
		return real_dbghelp.SymGetSymFromName64(hProcess, Name, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymNext (
		HANDLE           hProcess,
		PIMAGEHLP_SYMBOL Symbol
	) {
		return real_dbghelp.SymGetSymNext(hProcess, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymNext64 (
		HANDLE             hProcess,
		PIMAGEHLP_SYMBOL64 Symbol
	) {
		return real_dbghelp.SymGetSymNext64(hProcess, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymPrev (
		HANDLE           hProcess,
		PIMAGEHLP_SYMBOL Symbol
	) {
		return real_dbghelp.SymGetSymPrev(hProcess, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymPrev64 (
		HANDLE             hProcess,
		PIMAGEHLP_SYMBOL64 Symbol
	) {
		return real_dbghelp.SymGetSymPrev64(hProcess, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymbolFile (
		HANDLE hProcess,
		PCSTR  SymPath,
		PCSTR  ImageFile,
		DWORD  Type,
		PSTR   SymbolFile,
		size_t cSymbolFile,
		PSTR   DbgFile,
		size_t cDbgFile
	) {
		return real_dbghelp.SymGetSymbolFile(hProcess, SymPath, ImageFile, Type, SymbolFile, cSymbolFile, DbgFile, cDbgFile);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetSymbolFileW (
		HANDLE hProcess,
		PCWSTR SymPath,
		PCWSTR ImageFile,
		DWORD  Type,
		PWSTR  SymbolFile,
		size_t cSymbolFile,
		PWSTR  DbgFile,
		size_t cDbgFile
	) {
		return real_dbghelp.SymGetSymbolFileW(hProcess, SymPath, ImageFile, Type, SymbolFile, cSymbolFile, DbgFile, cDbgFile);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetTypeFromName (
		HANDLE       hProcess,
		ULONG64      BaseOfDll,
		PCSTR        Name,
		PSYMBOL_INFO Symbol
	) {
		return real_dbghelp.SymGetTypeFromName(hProcess, BaseOfDll, Name, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetTypeFromNameW (
		HANDLE        hProcess,
		ULONG64       BaseOfDll,
		PCWSTR        Name,
		PSYMBOL_INFOW Symbol
	) {
		return real_dbghelp.SymGetTypeFromNameW(hProcess, BaseOfDll, Name, Symbol);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetTypeInfo (
		HANDLE                    hProcess,
		DWORD64                   ModBase,
		ULONG                     TypeId,
		IMAGEHLP_SYMBOL_TYPE_INFO GetType,
		PVOID                     pInfo
	) {
		return real_dbghelp.SymGetTypeInfo(hProcess, ModBase, TypeId, GetType, pInfo);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymGetTypeInfoEx (
		HANDLE                         hProcess,
		DWORD64                        ModBase,
		PIMAGEHLP_GET_TYPE_INFO_PARAMS Params
	) {
		return real_dbghelp.SymGetTypeInfoEx(hProcess, ModBase, Params);
	}
	__declspec(dllexport) DWORD __stdcall hook_SymLoadModule (
		HANDLE hProcess,
		HANDLE hFile,
		PCSTR  ImageName,
		PCSTR  ModuleName,
		DWORD  BaseOfDll,
		DWORD  SizeOfDll
	) {
		return real_dbghelp.SymLoadModule(hProcess, hFile, ImageName, ModuleName, BaseOfDll, SizeOfDll);
	}
	__declspec(dllexport) DWORD64 __stdcall hook_SymLoadModule64 (
		HANDLE  hProcess,
		HANDLE  hFile,
		PCSTR   ImageName,
		PCSTR   ModuleName,
		DWORD64 BaseOfDll,
		DWORD   SizeOfDll
	) {
		return real_dbghelp.SymLoadModule64(hProcess, hFile, ImageName, ModuleName, BaseOfDll, SizeOfDll);
	}
	__declspec(dllexport) DWORD64 __stdcall hook_SymLoadModuleEx (
		HANDLE        hProcess,
		HANDLE        hFile,
		PCSTR         ImageName,
		PCSTR         ModuleName,
		DWORD64       BaseOfDll,
		DWORD         DllSize,
		PMODLOAD_DATA Data,
		DWORD         Flags
	) {
		return real_dbghelp.SymLoadModuleEx(hProcess, hFile, ImageName, ModuleName, BaseOfDll, DllSize, Data, Flags);
	}
	__declspec(dllexport) DWORD64 __stdcall hook_SymLoadModuleExW (
		HANDLE        hProcess,
		HANDLE        hFile,
		PCWSTR        ImageName,
		PCWSTR        ModuleName,
		DWORD64       BaseOfDll,
		DWORD         DllSize,
		PMODLOAD_DATA Data,
		DWORD         Flags
	) {
		return real_dbghelp.SymLoadModuleExW(hProcess, hFile, ImageName, ModuleName, BaseOfDll, DllSize, Data, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymMatchFileName (
		PCSTR FileName,
		PCSTR Match,
		PSTR* FileNameStop,
		PSTR* MatchStop
	) {
		return real_dbghelp.SymMatchFileName(FileName, Match, FileNameStop, MatchStop);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymMatchFileNameW (
		PCWSTR FileName,
		PCWSTR Match,
		PWSTR* FileNameStop,
		PWSTR* MatchStop
	) {
		return real_dbghelp.SymMatchFileNameW(FileName, Match, FileNameStop, MatchStop);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymMatchString (
		PCSTR string,
		PCSTR expression,
		BOOL  fCase
	) {
		return real_dbghelp.SymMatchString(string, expression, fCase);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymMatchStringA (
		PCSTR string,
		PCSTR expression,
		BOOL  fCase
	) {
		return real_dbghelp.SymMatchStringA(string, expression, fCase);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymMatchStringW (
		PCWSTR string,
		PCWSTR expression,
		BOOL   fCase
	) {
		return real_dbghelp.SymMatchStringW(string, expression, fCase);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymNext (
		HANDLE       hProcess,
		PSYMBOL_INFO si
	) {
		return real_dbghelp.SymNext(hProcess, si);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymNextW (
		HANDLE        hProcess,
		PSYMBOL_INFOW siw
	) {
		return real_dbghelp.SymNextW(hProcess, siw);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymPrev (
		HANDLE       hProcess,
		PSYMBOL_INFO si
	) {
		return real_dbghelp.SymPrev(hProcess, si);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymPrevW (
		HANDLE        hProcess,
		PSYMBOL_INFOW siw
	) {
		return real_dbghelp.SymPrevW(hProcess, siw);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymRefreshModuleList (
		HANDLE hProcess
	) {
		return real_dbghelp.SymRefreshModuleList(hProcess);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymRegisterCallback (
		HANDLE                      hProcess,
		PSYMBOL_REGISTERED_CALLBACK CallbackFunction,
		PVOID                       UserContext
	) {
		return real_dbghelp.SymRegisterCallback(hProcess, CallbackFunction, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymRegisterCallback64 (
		HANDLE                        hProcess,
		PSYMBOL_REGISTERED_CALLBACK64 CallbackFunction,
		ULONG64                       UserContext
	) {
		return real_dbghelp.SymRegisterCallback64(hProcess, CallbackFunction, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymRegisterCallbackW64 (
		HANDLE                        hProcess,
		PSYMBOL_REGISTERED_CALLBACK64 CallbackFunction,
		ULONG64                       UserContext
	) {
		return real_dbghelp.SymRegisterCallbackW64(hProcess, CallbackFunction, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymRegisterFunctionEntryCallback (
		HANDLE                     hProcess,
		PSYMBOL_FUNCENTRY_CALLBACK CallbackFunction,
		PVOID                      UserContext
	) {
		return real_dbghelp.SymRegisterFunctionEntryCallback(hProcess, CallbackFunction, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymRegisterFunctionEntryCallback64 (
		HANDLE                       hProcess,
		PSYMBOL_FUNCENTRY_CALLBACK64 CallbackFunction,
		ULONG64                      UserContext
	) {
		return real_dbghelp.SymRegisterFunctionEntryCallback64(hProcess, CallbackFunction, UserContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSearch (
		HANDLE                         hProcess,
		ULONG64                        BaseOfDll,
		DWORD                          Index,
		DWORD                          SymTag,
		PCSTR                          Mask,
		DWORD64                        Address,
		PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
		PVOID                          UserContext,
		DWORD                          Options
	) {
		return real_dbghelp.SymSearch(hProcess, BaseOfDll, Index, SymTag, Mask, Address, EnumSymbolsCallback, UserContext, Options);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSearchW (
		HANDLE                          hProcess,
		ULONG64                         BaseOfDll,
		DWORD                           Index,
		DWORD                           SymTag,
		PCWSTR                          Mask,
		DWORD64                         Address,
		PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
		PVOID                           UserContext,
		DWORD                           Options
	) {
		return real_dbghelp.SymSearchW(hProcess, BaseOfDll, Index, SymTag, Mask, Address, EnumSymbolsCallback, UserContext, Options);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetContext (
		HANDLE                hProcess,
		PIMAGEHLP_STACK_FRAME StackFrame,
		PIMAGEHLP_CONTEXT     Context
	) {
		return real_dbghelp.SymSetContext(hProcess, StackFrame, Context);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetExtendedOption (
		IMAGEHLP_EXTENDED_OPTIONS option,
		BOOL                      value
	) {
		return real_dbghelp.SymSetExtendedOption(option, value);
	}
	__declspec(dllexport) PCHAR __stdcall hook_SymSetHomeDirectory (
		HANDLE hProcess,
		PCSTR  dir
	) {
		return real_dbghelp.SymSetHomeDirectory(hProcess, dir);
	}
	__declspec(dllexport) PWSTR __stdcall hook_SymSetHomeDirectoryW (
		HANDLE hProcess,
		PCWSTR dir
	) {
		return real_dbghelp.SymSetHomeDirectoryW(hProcess, dir);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetParentWindow (
		HWND hwnd
	) {
		return real_dbghelp.SymSetParentWindow(hwnd);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetScopeFromAddr (
		HANDLE  hProcess,
		ULONG64 Address
	) {
		return real_dbghelp.SymSetScopeFromAddr(hProcess, Address);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetScopeFromIndex (
		HANDLE  hProcess,
		ULONG64 BaseOfDll,
		DWORD   Index
	) {
		return real_dbghelp.SymSetScopeFromIndex(hProcess, BaseOfDll, Index);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetScopeFromInlineContext (
		HANDLE  hProcess,
		ULONG64 Address,
		ULONG   InlineContext
	) {
		return real_dbghelp.SymSetScopeFromInlineContext(hProcess, Address, InlineContext);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetSearchPath (
		HANDLE hProcess,
		PCSTR  SearchPath
	) {
		return real_dbghelp.SymSetSearchPath(hProcess, SearchPath);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSetSearchPathW (
		HANDLE hProcess,
		PCWSTR SearchPath
	) {
		return real_dbghelp.SymSetSearchPathW(hProcess, SearchPath);
	}
	__declspec(dllexport) PCSTR __stdcall hook_SymSrvDeltaName (
		HANDLE hProcess,
		PCSTR  SymPath,
		PCSTR  Type,
		PCSTR  File1,
		PCSTR  File2
	) {
		return real_dbghelp.SymSrvDeltaName(hProcess, SymPath, Type, File1, File2);
	}
	__declspec(dllexport) PCWSTR __stdcall hook_SymSrvDeltaNameW (
		HANDLE hProcess,
		PCWSTR SymPath,
		PCWSTR Type,
		PCWSTR File1,
		PCWSTR File2
	) {
		return real_dbghelp.SymSrvDeltaNameW(hProcess, SymPath, Type, File1, File2);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvGetFileIndexInfo (
		PCSTR              File,
		PSYMSRV_INDEX_INFO Info,
		DWORD              Flags
	) {
		return real_dbghelp.SymSrvGetFileIndexInfo(File, Info, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvGetFileIndexInfoW (
		PCWSTR              File,
		PSYMSRV_INDEX_INFOW Info,
		DWORD               Flags
	) {
		return real_dbghelp.SymSrvGetFileIndexInfoW(File, Info, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvGetFileIndexString (
		HANDLE hProcess,
		PCSTR  SrvPath,
		PCSTR  File,
		PSTR   Index,
		size_t Size,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvGetFileIndexString(hProcess, SrvPath, File, Index, Size, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvGetFileIndexStringW (
		HANDLE hProcess,
		PCWSTR SrvPath,
		PCWSTR File,
		PWSTR  Index,
		size_t Size,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvGetFileIndexStringW(hProcess, SrvPath, File, Index, Size, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvGetFileIndexes (
		PCSTR  File,
		GUID* Id,
		PDWORD Val1,
		PDWORD Val2,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvGetFileIndexes(File, Id, Val1, Val2, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvGetFileIndexesW (
		PCWSTR File,
		GUID* Id,
		PDWORD Val1,
		PDWORD Val2,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvGetFileIndexesW(File, Id, Val1, Val2, Flags);
	}
	__declspec(dllexport) PCSTR __stdcall hook_SymSrvGetSupplement (
		HANDLE hProcess,
		PCSTR  SymPath,
		PCSTR  Node,
		PCSTR  File
	) {
		return real_dbghelp.SymSrvGetSupplement(hProcess, SymPath, Node, File);
	}
	__declspec(dllexport) PCWSTR __stdcall hook_SymSrvGetSupplementW (
		HANDLE hProcess,
		PCWSTR SymPath,
		PCWSTR Node,
		PCWSTR File
	) {
		return real_dbghelp.SymSrvGetSupplementW(hProcess, SymPath, Node, File);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvIsStore (
		HANDLE hProcess,
		PCSTR  path
	) {
		return real_dbghelp.SymSrvIsStore(hProcess, path);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymSrvIsStoreW (
		HANDLE hProcess,
		PCWSTR path
	) {
		return real_dbghelp.SymSrvIsStoreW(hProcess, path);
	}
	__declspec(dllexport) PCSTR __stdcall hook_SymSrvStoreFile (
		HANDLE hProcess,
		PCSTR  SrvPath,
		PCSTR  File,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvStoreFile(hProcess, SrvPath, File, Flags);
	}
	__declspec(dllexport) PCWSTR __stdcall hook_SymSrvStoreFileW (
		HANDLE hProcess,
		PCWSTR SrvPath,
		PCWSTR File,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvStoreFileW(hProcess, SrvPath, File, Flags);
	}
	__declspec(dllexport) PCSTR __stdcall hook_SymSrvStoreSupplement (
		HANDLE hProcess,
		PCSTR  SrvPath,
		PCSTR  Node,
		PCSTR  File,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvStoreSupplement(hProcess, SrvPath, Node, File, Flags);
	}
	__declspec(dllexport) PCWSTR __stdcall hook_SymSrvStoreSupplementW (
		HANDLE hProcess,
		PCWSTR SymPath,
		PCWSTR Node,
		PCWSTR File,
		DWORD  Flags
	) {
		return real_dbghelp.SymSrvStoreSupplementW(hProcess, SymPath, Node, File, Flags);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymUnDName (
		PIMAGEHLP_SYMBOL sym,
		PSTR             UnDecName,
		DWORD            UnDecNameLength
	) {
		return real_dbghelp.SymUnDName(sym, UnDecName, UnDecNameLength);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymUnDName64 (
		PIMAGEHLP_SYMBOL64 sym,
		PSTR               UnDecName,
		DWORD              UnDecNameLength
	) {
		return real_dbghelp.SymUnDName64(sym, UnDecName, UnDecNameLength);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymUnloadModule (
		HANDLE hProcess,
		DWORD  BaseOfDll
	) {
		return real_dbghelp.SymUnloadModule(hProcess, BaseOfDll);
	}
	__declspec(dllexport) BOOL __stdcall hook_SymUnloadModule64 (
		HANDLE  hProcess,
		DWORD64 BaseOfDll
	) {
		return real_dbghelp.SymUnloadModule64(hProcess, BaseOfDll);
	}
	__declspec(dllexport) DWORD __stdcall hook_UnDecorateSymbolName (
		PCSTR name,
		PSTR  outputString,
		DWORD maxStringLength,
		DWORD flags
	) {
		return real_dbghelp.UnDecorateSymbolName(name, outputString, maxStringLength, flags);
	}
	__declspec(dllexport) DWORD __stdcall hook_UnDecorateSymbolNameW (
		PCWSTR name,
		PWSTR  outputString,
		DWORD  maxStringLength,
		DWORD  flags
	) {
		return real_dbghelp.UnDecorateSymbolNameW(name, outputString, maxStringLength, flags);
	}
}
