#pragma once
#include "util.hpp"

// dbghelp.h would normally define dllimport functions, but we're trying to make a dll mimicing dbghelp.dll here
// by defining _IMAGEHLP_SOURCE_, the header declares the functions without dllimport, which we then ignore and export custom wrapper ones
// but we need all the types structs and function pointer typdefs (callbacks) to delegate to the original dll
// (despite the fact that delegating a function call could simply be done with a single jmp instruction)
#define _IMAGEHLP_SOURCE_
#include <dbghelp.h>

/*
These functions are exported by dbghelp.dll but there is no documentation on them

These exist in DbgHelp.h
DbgHelpCreateUserDump
DbgHelpCreateUserDumpW
FindFileInPath
FindFileInSearchPath
RemoveInvalidModuleList
ReportSymbolLoadSummary
SetCheckUserInterruptShared
SymEnumSym

These have no documentation and do not exist directly in DbgHelp.h
  so I have no idea how to even forward these calls,
  but it's unlikely that any program will call them anyway
ExtensionApiVersion
RangeMap*
SymGetLineFromAddrEx
SymGetLineFromNameEx
SymGetLineNextEx
SymGetLinePrevEx
SymGetOmapBlockBase
SymAllocDiaString
SymFreeDiaString
SymGetDiaSession
SymSetDiaSession
WinDbgExtensionDllInit

// Undocumented function but found in DbgHelp.h
// not forwarded for now

BOOL
WINAPI
DbgHelpCreateUserDump(
	_In_opt_ LPCSTR FileName,
	_In_ PDBGHELP_CREATE_USER_DUMP_CALLBACK Callback,
	_In_opt_ PVOID UserData
	);

BOOL
WINAPI
DbgHelpCreateUserDumpW(
	_In_opt_ LPCWSTR FileName,
	_In_ PDBGHELP_CREATE_USER_DUMP_CALLBACK Callback,
	_In_opt_ PVOID UserData
	);

DBHLP_DEPRECIATED
BOOL
IMAGEAPI
FindFileInPath(
	_In_ HANDLE hprocess,
	_In_ PCSTR SearchPath,
	_In_ PCSTR FileName,
	_In_ PVOID id,
	_In_ DWORD two,
	_In_ DWORD three,
	_In_ DWORD flags,
	_Out_writes_(MAX_PATH + 1) PSTR FilePath
	);

DBHLP_DEPRECIATED
BOOL
IMAGEAPI
FindFileInSearchPath(
	_In_ HANDLE hprocess,
	_In_ PCSTR SearchPath,
	_In_ PCSTR FileName,
	_In_ DWORD one,
	_In_ DWORD two,
	_In_ DWORD three,
	_Out_writes_(MAX_PATH + 1) PSTR FilePath
	);

void
IMAGEAPI
RemoveInvalidModuleList(
	_In_ HANDLE hProcess
	);

BOOL
IMAGEAPI
ReportSymbolLoadSummary(
	_In_ HANDLE hProcess,
	_In_opt_ PCWSTR pLoadModule,
	_In_ PDBGHELP_DATA_REPORT_STRUCT pSymbolData
	);

void
IMAGEAPI
SetCheckUserInterruptShared(
	_In_ LPCALL_BACK_USER_INTERRUPT_ROUTINE lpStartAddress
	);


BOOL
IMAGEAPI
SymGetUnwindInfo(
	_In_ HANDLE hProcess,
	_In_ DWORD64 Address,
	_Out_writes_bytes_opt_(*Size) PVOID Buffer,
	_Inout_ PULONG Size
	);
*/

////
// Autogenerated by script
////

// =============================================================
// Function Typdefs
typedef BOOL (__stdcall* t_EnumDirTree) (
	HANDLE                hProcess,
	PCSTR                 RootPath,
	PCSTR                 InputPathName,
	PSTR                  OutputPathBuffer,
	PENUMDIRTREE_CALLBACK cb,
	PVOID                 data
	);
typedef BOOL (__stdcall* t_EnumDirTreeW) (
	HANDLE                 hProcess,
	PCWSTR                 RootPath,
	PCWSTR                 InputPathName,
	PWSTR                  OutputPathBuffer,
	PENUMDIRTREE_CALLBACKW cb,
	PVOID                  data
	);
typedef BOOL (__stdcall* t_EnumerateLoadedModules) (
	HANDLE                       hProcess,
	PENUMLOADED_MODULES_CALLBACK EnumLoadedModulesCallback,
	PVOID                        UserContext
	);
typedef BOOL (__stdcall* t_EnumerateLoadedModules64) (
	HANDLE                         hProcess,
	PENUMLOADED_MODULES_CALLBACK64 EnumLoadedModulesCallback,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_EnumerateLoadedModulesEx) (
	HANDLE                         hProcess,
	PENUMLOADED_MODULES_CALLBACK64 EnumLoadedModulesCallback,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_EnumerateLoadedModulesExW) (
	HANDLE                          hProcess,
	PENUMLOADED_MODULES_CALLBACKW64 EnumLoadedModulesCallback,
	PVOID                           UserContext
	);
typedef BOOL (__stdcall* t_EnumerateLoadedModulesW64) (
	HANDLE                          hProcess,
	PENUMLOADED_MODULES_CALLBACKW64 EnumLoadedModulesCallback,
	PVOID                           UserContext
	);
typedef HANDLE (__stdcall* t_FindDebugInfoFile) (
	PCSTR FileName,
	PCSTR SymbolPath,
	PSTR  DebugFilePath
	);
typedef HANDLE (__stdcall* t_FindDebugInfoFileEx) (
	PCSTR                     FileName,
	PCSTR                     SymbolPath,
	PSTR                      DebugFilePath,
	PFIND_DEBUG_FILE_CALLBACK Callback,
	PVOID                     CallerData
	);
typedef HANDLE (__stdcall* t_FindDebugInfoFileExW) (
	PCWSTR                     FileName,
	PCWSTR                     SymbolPath,
	PWSTR                      DebugFilePath,
	PFIND_DEBUG_FILE_CALLBACKW Callback,
	PVOID                      CallerData
	);
typedef HANDLE (__stdcall* t_FindExecutableImage) (
	PCSTR FileName,
	PCSTR SymbolPath,
	PSTR  ImageFilePath
	);
typedef HANDLE (__stdcall* t_FindExecutableImageEx) (
	PCSTR                   FileName,
	PCSTR                   SymbolPath,
	PSTR                    ImageFilePath,
	PFIND_EXE_FILE_CALLBACK Callback,
	PVOID                   CallerData
	);
typedef HANDLE (__stdcall* t_FindExecutableImageExW) (
	PCWSTR                   FileName,
	PCWSTR                   SymbolPath,
	PWSTR                    ImageFilePath,
	PFIND_EXE_FILE_CALLBACKW Callback,
	PVOID                    CallerData
	);
typedef DWORD (__stdcall* t_GetSymLoadError) ();
typedef DWORD (__stdcall* t_GetTimestampForLoadedLibrary) (
	HMODULE Module
	);
typedef PVOID (__stdcall* t_ImageDirectoryEntryToData) (
	PVOID   Base,
	BOOLEAN MappedAsImage,
	USHORT  DirectoryEntry,
	PULONG  Size
	);
typedef PVOID (__stdcall* t_ImageDirectoryEntryToDataEx) (
	PVOID                 Base,
	BOOLEAN               MappedAsImage,
	USHORT                DirectoryEntry,
	PULONG                Size,
	PIMAGE_SECTION_HEADER* FoundHeader
	);
typedef PIMAGE_NT_HEADERS (__stdcall* t_ImageNtHeader) (
	PVOID Base
	);
typedef PIMAGE_SECTION_HEADER (__stdcall* t_ImageRvaToSection) (
	PIMAGE_NT_HEADERS NtHeaders,
	PVOID             Base,
	ULONG             Rva
	);
typedef PVOID (__stdcall* t_ImageRvaToVa) (
	PIMAGE_NT_HEADERS     NtHeaders,
	PVOID                 Base,
	ULONG                 Rva,
	PIMAGE_SECTION_HEADER* LastRvaSection
	);
typedef LPAPI_VERSION (__stdcall* t_ImagehlpApiVersion) ();
typedef LPAPI_VERSION (__stdcall* t_ImagehlpApiVersionEx) (
	LPAPI_VERSION AppVersion
	);
typedef BOOL (__stdcall* t_MakeSureDirectoryPathExists) (
	PCSTR DirPath
	);
typedef BOOL (__stdcall* t_MiniDumpReadDumpStream) (
	PVOID               BaseOfDump,
	ULONG               StreamNumber,
	PMINIDUMP_DIRECTORY* Dir,
	PVOID* StreamPointer,
	ULONG* StreamSize
	);
typedef BOOL (__stdcall* t_MiniDumpWriteDump) (
	HANDLE                            hProcess,
	DWORD                             ProcessId,
	HANDLE                            hFile,
	MINIDUMP_TYPE                     DumpType,
	PMINIDUMP_EXCEPTION_INFORMATION   ExceptionParam,
	PMINIDUMP_USER_STREAM_INFORMATION UserStreamParam,
	PMINIDUMP_CALLBACK_INFORMATION    CallbackParam
	);
typedef BOOL (__stdcall* t_SearchTreeForFile) (
	PCSTR RootPath,
	PCSTR InputPathName,
	PSTR  OutputPathBuffer
	);
typedef BOOL (__stdcall* t_SearchTreeForFileW) (
	PCWSTR RootPath,
	PCWSTR InputPathName,
	PWSTR  OutputPathBuffer
	);
typedef void (__stdcall* t_SetSymLoadError) (
	DWORD error
	);
typedef BOOL (__stdcall* t_StackWalk) (
	DWORD                          MachineType,
	HANDLE                         hProcess,
	HANDLE                         hThread,
	LPSTACKFRAME                   StackFrame,
	PVOID                          ContextRecord,
	PREAD_PROCESS_MEMORY_ROUTINE   ReadMemoryRoutine,
	PFUNCTION_TABLE_ACCESS_ROUTINE FunctionTableAccessRoutine,
	PGET_MODULE_BASE_ROUTINE       GetModuleBaseRoutine,
	PTRANSLATE_ADDRESS_ROUTINE     TranslateAddress
	);
typedef BOOL (__stdcall* t_StackWalk64) (
	DWORD                            MachineType,
	HANDLE                           hProcess,
	HANDLE                           hThread,
	LPSTACKFRAME64                   StackFrame,
	PVOID                            ContextRecord,
	PREAD_PROCESS_MEMORY_ROUTINE64   ReadMemoryRoutine,
	PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine,
	PGET_MODULE_BASE_ROUTINE64       GetModuleBaseRoutine,
	PTRANSLATE_ADDRESS_ROUTINE64     TranslateAddress
	);
typedef BOOL (__stdcall* t_StackWalkEx) (
	DWORD                            MachineType,
	HANDLE                           hProcess,
	HANDLE                           hThread,
	LPSTACKFRAME_EX                  StackFrame,
	PVOID                            ContextRecord,
	PREAD_PROCESS_MEMORY_ROUTINE64   ReadMemoryRoutine,
	PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine,
	PGET_MODULE_BASE_ROUTINE64       GetModuleBaseRoutine,
	PTRANSLATE_ADDRESS_ROUTINE64     TranslateAddress,
	DWORD                            Flags
	);
typedef BOOL (__stdcall* t_SymAddSourceStream) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCSTR   StreamFile,
	PBYTE   Buffer,
	size_t  Size
	);
typedef BOOL (__stdcall* t_SymAddSourceStreamA) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCSTR   StreamFile,
	PBYTE   Buffer,
	size_t  Size
	);
typedef BOOL (__stdcall* t_SymAddSourceStreamW) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCWSTR  FileSpec,
	PBYTE   Buffer,
	size_t  Size
	);
typedef BOOL (__stdcall* t_SymAddSymbol) (
	HANDLE  hProcess,
	ULONG64 BaseOfDll,
	PCSTR   Name,
	DWORD64 Address,
	DWORD   Size,
	DWORD   Flags
	);
typedef BOOL (__stdcall* t_SymAddSymbolW) (
	HANDLE  hProcess,
	ULONG64 BaseOfDll,
	PCWSTR  Name,
	DWORD64 Address,
	DWORD   Size,
	DWORD   Flags
	);
typedef DWORD (__stdcall* t_SymAddrIncludeInlineTrace) (
	HANDLE  hProcess,
	DWORD64 Address
	);
typedef BOOL (__stdcall* t_SymCleanup) (
	HANDLE hProcess
	);
typedef DWORD (__stdcall* t_SymCompareInlineTrace) (
	HANDLE  hProcess,
	DWORD64 Address1,
	DWORD   InlineContext1,
	DWORD64 RetAddress1,
	DWORD64 Address2,
	DWORD64 RetAddress2
	);
typedef BOOL (__stdcall* t_SymDeleteSymbol) (
	HANDLE  hProcess,
	ULONG64 BaseOfDll,
	PCSTR   Name,
	DWORD64 Address,
	DWORD   Flags
	);
typedef BOOL (__stdcall* t_SymDeleteSymbolW) (
	HANDLE  hProcess,
	ULONG64 BaseOfDll,
	PCWSTR  Name,
	DWORD64 Address,
	DWORD   Flags
	);
typedef BOOL (__stdcall* t_SymEnumLines) (
	HANDLE                  hProcess,
	ULONG64                 Base,
	PCSTR                   Obj,
	PCSTR                   File,
	PSYM_ENUMLINES_CALLBACK EnumLinesCallback,
	PVOID                   UserContext
	);
typedef BOOL (__stdcall* t_SymEnumLinesW) (
	HANDLE                   hProcess,
	ULONG64                  Base,
	PCWSTR                   Obj,
	PCWSTR                   File,
	PSYM_ENUMLINES_CALLBACKW EnumLinesCallback,
	PVOID                    UserContext
	);
typedef BOOL (__stdcall* t_SymEnumProcesses) (
	PSYM_ENUMPROCESSES_CALLBACK EnumProcessesCallback,
	PVOID                       UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSourceFileTokens) (
	HANDLE                        hProcess,
	ULONG64                       Base,
	PENUMSOURCEFILETOKENSCALLBACK Callback
	);
typedef BOOL (__stdcall* t_SymEnumSourceFiles) (
	HANDLE                        hProcess,
	ULONG64                       ModBase,
	PCSTR                         Mask,
	PSYM_ENUMSOURCEFILES_CALLBACK cbSrcFiles,
	PVOID                         UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSourceFilesW) (
	HANDLE                         hProcess,
	ULONG64                        ModBase,
	PCWSTR                         Mask,
	PSYM_ENUMSOURCEFILES_CALLBACKW cbSrcFiles,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSourceLines) (
	HANDLE                  hProcess,
	ULONG64                 Base,
	PCSTR                   Obj,
	PCSTR                   File,
	DWORD                   Line,
	DWORD                   Flags,
	PSYM_ENUMLINES_CALLBACK EnumLinesCallback,
	PVOID                   UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSourceLinesW) (
	HANDLE                   hProcess,
	ULONG64                  Base,
	PCWSTR                   Obj,
	PCWSTR                   File,
	DWORD                    Line,
	DWORD                    Flags,
	PSYM_ENUMLINES_CALLBACKW EnumLinesCallback,
	PVOID                    UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSymbols) (
	HANDLE                         hProcess,
	ULONG64                        BaseOfDll,
	PCSTR                          Mask,
	PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSymbolsEx) (
	HANDLE                         hProcess,
	ULONG64                        BaseOfDll,
	PCSTR                          Mask,
	PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                          UserContext,
	DWORD                          Options
	);
typedef BOOL (__stdcall* t_SymEnumSymbolsExW) (
	HANDLE                          hProcess,
	ULONG64                         BaseOfDll,
	PCWSTR                          Mask,
	PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                           UserContext,
	DWORD                           Options
	);
typedef BOOL (__stdcall* t_SymEnumSymbolsForAddr) (
	HANDLE                         hProcess,
	DWORD64                        Address,
	PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSymbolsForAddrW) (
	HANDLE                          hProcess,
	DWORD64                         Address,
	PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                           UserContext
	);
typedef BOOL (__stdcall* t_SymEnumSymbolsW) (
	HANDLE                          hProcess,
	ULONG64                         BaseOfDll,
	PCWSTR                          Mask,
	PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                           UserContext
	);
typedef BOOL (__stdcall* t_SymEnumTypes) (
	HANDLE                         hProcess,
	ULONG64                        BaseOfDll,
	PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_SymEnumTypesByName) (
	HANDLE                         hProcess,
	ULONG64                        BaseOfDll,
	PCSTR                          mask,
	PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                          UserContext
	);
typedef BOOL (__stdcall* t_SymEnumTypesByNameW) (
	HANDLE                          hProcess,
	ULONG64                         BaseOfDll,
	PCWSTR                          mask,
	PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                           UserContext
	);
typedef BOOL (__stdcall* t_SymEnumTypesW) (
	HANDLE                          hProcess,
	ULONG64                         BaseOfDll,
	PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                           UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateModules) (
	HANDLE                    hProcess,
	PSYM_ENUMMODULES_CALLBACK EnumModulesCallback,
	PVOID                     UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateModules64) (
	HANDLE                      hProcess,
	PSYM_ENUMMODULES_CALLBACK64 EnumModulesCallback,
	PVOID                       UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateModulesW64) (
	HANDLE                       hProcess,
	PSYM_ENUMMODULES_CALLBACKW64 EnumModulesCallback,
	PVOID                        UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateSymbols) (
	HANDLE                    hProcess,
	ULONG                     BaseOfDll,
	PSYM_ENUMSYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                     UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateSymbols64) (
	HANDLE                      hProcess,
	ULONG64                     BaseOfDll,
	PSYM_ENUMSYMBOLS_CALLBACK64 EnumSymbolsCallback,
	PVOID                       UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateSymbolsW) (
	HANDLE                     hProcess,
	ULONG                      BaseOfDll,
	PSYM_ENUMSYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                      UserContext
	);
typedef BOOL (__stdcall* t_SymEnumerateSymbolsW64) (
	HANDLE                       hProcess,
	ULONG64                      BaseOfDll,
	PSYM_ENUMSYMBOLS_CALLBACK64W EnumSymbolsCallback,
	PVOID                        UserContext
	);
typedef HANDLE (__stdcall* t_SymFindDebugInfoFile) (
	HANDLE                    hProcess,
	PCSTR                     FileName,
	PSTR                      DebugFilePath,
	PFIND_DEBUG_FILE_CALLBACK Callback,
	PVOID                     CallerData
	);
typedef HANDLE (__stdcall* t_SymFindDebugInfoFileW) (
	HANDLE                     hProcess,
	PCWSTR                     FileName,
	PWSTR                      DebugFilePath,
	PFIND_DEBUG_FILE_CALLBACKW Callback,
	PVOID                      CallerData
	);
typedef HANDLE (__stdcall* t_SymFindExecutableImage) (
	HANDLE                  hProcess,
	PCSTR                   FileName,
	PSTR                    ImageFilePath,
	PFIND_EXE_FILE_CALLBACK Callback,
	PVOID                   CallerData
	);
typedef HANDLE (__stdcall* t_SymFindExecutableImageW) (
	HANDLE                   hProcess,
	PCWSTR                   FileName,
	PWSTR                    ImageFilePath,
	PFIND_EXE_FILE_CALLBACKW Callback,
	PVOID                    CallerData
	);
typedef BOOL (__stdcall* t_SymFindFileInPath) (
	HANDLE                  hprocess,
	PCSTR                   SearchPath,
	PCSTR                   FileName,
	PVOID                   id,
	DWORD                   two,
	DWORD                   three,
	DWORD                   flags,
	PSTR                    FoundFile,
	PFINDFILEINPATHCALLBACK callback,
	PVOID                   context
	);
typedef BOOL (__stdcall* t_SymFindFileInPathW) (
	HANDLE                   hprocess,
	PCWSTR                   SearchPath,
	PCWSTR                   FileName,
	PVOID                    id,
	DWORD                    two,
	DWORD                    three,
	DWORD                    flags,
	PWSTR                    FoundFile,
	PFINDFILEINPATHCALLBACKW callback,
	PVOID                    context
	);
typedef BOOL (__stdcall* t_SymFromAddr) (
	HANDLE       hProcess,
	DWORD64      Address,
	PDWORD64     Displacement,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymFromAddrW) (
	HANDLE        hProcess,
	DWORD64       Address,
	PDWORD64      Displacement,
	PSYMBOL_INFOW Symbol
	);
typedef BOOL (__stdcall* t_SymFromIndex) (
	HANDLE       hProcess,
	ULONG64      BaseOfDll,
	DWORD        Index,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymFromIndexW) (
	HANDLE        hProcess,
	ULONG64       BaseOfDll,
	DWORD         Index,
	PSYMBOL_INFOW Symbol
	);
typedef BOOL (__stdcall* t_SymFromInlineContext) (
	HANDLE       hProcess,
	DWORD64      Address,
	ULONG        InlineContext,
	PDWORD64     Displacement,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymFromInlineContextW) (
	HANDLE        hProcess,
	DWORD64       Address,
	ULONG         InlineContext,
	PDWORD64      Displacement,
	PSYMBOL_INFOW Symbol
	);
typedef BOOL (__stdcall* t_SymFromName) (
	HANDLE       hProcess,
	PCSTR        Name,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymFromNameW) (
	HANDLE        hProcess,
	PCWSTR        Name,
	PSYMBOL_INFOW Symbol
	);
typedef BOOL (__stdcall* t_SymFromToken) (
	HANDLE       hProcess,
	DWORD64      Base,
	DWORD        Token,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymFromTokenW) (
	HANDLE        hProcess,
	DWORD64       Base,
	DWORD         Token,
	PSYMBOL_INFOW Symbol
	);
typedef PVOID (__stdcall* t_SymFunctionTableAccess) (
	HANDLE hProcess,
	DWORD  AddrBase
	);
typedef PVOID (__stdcall* t_SymFunctionTableAccess64) (
	HANDLE  hProcess,
	DWORD64 AddrBase
	);
typedef PVOID (__stdcall* t_SymFunctionTableAccess64AccessRoutines) (
	HANDLE                         hProcess,
	DWORD64                        AddrBase,
	PREAD_PROCESS_MEMORY_ROUTINE64 ReadMemoryRoutine,
	PGET_MODULE_BASE_ROUTINE64     GetModuleBaseRoutine
	);
typedef BOOL (__stdcall* t_SymGetExtendedOption) (
	IMAGEHLP_EXTENDED_OPTIONS option
	);
typedef ULONG (__stdcall* t_SymGetFileLineOffsets64) (
	HANDLE   hProcess,
	PCSTR    ModuleName,
	PCSTR    FileName,
	PDWORD64 Buffer,
	ULONG    BufferLines
	);
typedef PCHAR (__stdcall* t_SymGetHomeDirectory) (
	DWORD  type,
	PSTR   dir,
	size_t size
	);
typedef PWSTR (__stdcall* t_SymGetHomeDirectoryW) (
	DWORD  type,
	PWSTR  dir,
	size_t size
	);
typedef BOOL (__stdcall* t_SymGetLineFromAddr) (
	HANDLE         hProcess,
	DWORD          dwAddr,
	PDWORD         pdwDisplacement,
	PIMAGEHLP_LINE Line
	);
typedef BOOL (__stdcall* t_SymGetLineFromAddr64) (
	HANDLE           hProcess,
	DWORD64          qwAddr,
	PDWORD           pdwDisplacement,
	PIMAGEHLP_LINE64 Line64
	);
typedef BOOL (__stdcall* t_SymGetLineFromAddrW64) (
	HANDLE            hProcess,
	DWORD64           dwAddr,
	PDWORD            pdwDisplacement,
	PIMAGEHLP_LINEW64 Line
	);
typedef BOOL (__stdcall* t_SymGetLineFromInlineContext) (
	HANDLE           hProcess,
	DWORD64          qwAddr,
	ULONG            InlineContext,
	DWORD64          qwModuleBaseAddress,
	PDWORD           pdwDisplacement,
	PIMAGEHLP_LINE64 Line64
	);
typedef BOOL (__stdcall* t_SymGetLineFromInlineContextW) (
	HANDLE            hProcess,
	DWORD64           dwAddr,
	ULONG             InlineContext,
	DWORD64           qwModuleBaseAddress,
	PDWORD            pdwDisplacement,
	PIMAGEHLP_LINEW64 Line
	);
typedef BOOL (__stdcall* t_SymGetLineFromName) (
	HANDLE         hProcess,
	PCSTR          ModuleName,
	PCSTR          FileName,
	DWORD          dwLineNumber,
	PLONG          plDisplacement,
	PIMAGEHLP_LINE Line
	);
typedef BOOL (__stdcall* t_SymGetLineFromName64) (
	HANDLE           hProcess,
	PCSTR            ModuleName,
	PCSTR            FileName,
	DWORD            dwLineNumber,
	PLONG            plDisplacement,
	PIMAGEHLP_LINE64 Line
	);
typedef BOOL (__stdcall* t_SymGetLineFromNameW64) (
	HANDLE            hProcess,
	PCWSTR            ModuleName,
	PCWSTR            FileName,
	DWORD             dwLineNumber,
	PLONG             plDisplacement,
	PIMAGEHLP_LINEW64 Line
	);
typedef BOOL (__stdcall* t_SymGetLineNext) (
	HANDLE         hProcess,
	PIMAGEHLP_LINE Line
	);
typedef BOOL (__stdcall* t_SymGetLineNext64) (
	HANDLE           hProcess,
	PIMAGEHLP_LINE64 Line
	);
typedef BOOL (__stdcall* t_SymGetLineNextW64) (
	HANDLE            hProcess,
	PIMAGEHLP_LINEW64 Line
	);
typedef BOOL (__stdcall* t_SymGetLinePrev) (
	HANDLE         hProcess,
	PIMAGEHLP_LINE Line
	);
typedef BOOL (__stdcall* t_SymGetLinePrev64) (
	HANDLE           hProcess,
	PIMAGEHLP_LINE64 Line
	);
typedef BOOL (__stdcall* t_SymGetLinePrevW64) (
	HANDLE            hProcess,
	PIMAGEHLP_LINEW64 Line
	);
typedef DWORD (__stdcall* t_SymGetModuleBase) (
	HANDLE hProcess,
	DWORD  dwAddr
	);
typedef DWORD64 (__stdcall* t_SymGetModuleBase64) (
	HANDLE  hProcess,
	DWORD64 qwAddr
	);
typedef BOOL (__stdcall* t_SymGetModuleInfo) (
	HANDLE           hProcess,
	DWORD            dwAddr,
	PIMAGEHLP_MODULE ModuleInfo
	);
typedef BOOL (__stdcall* t_SymGetModuleInfo64) (
	HANDLE             hProcess,
	DWORD64            qwAddr,
	PIMAGEHLP_MODULE64 ModuleInfo
	);
typedef BOOL (__stdcall* t_SymGetModuleInfoW) (
	HANDLE            hProcess,
	DWORD             dwAddr,
	PIMAGEHLP_MODULEW ModuleInfo
	);
typedef BOOL (__stdcall* t_SymGetModuleInfoW64) (
	HANDLE              hProcess,
	DWORD64             qwAddr,
	PIMAGEHLP_MODULEW64 ModuleInfo
	);
typedef BOOL (__stdcall* t_SymGetOmaps) (
	HANDLE   hProcess,
	DWORD64  BaseOfDll,
	POMAP* OmapTo,
	PDWORD64 cOmapTo,
	POMAP* OmapFrom,
	PDWORD64 cOmapFrom
	);
typedef DWORD (__stdcall* t_SymGetOptions) ();
typedef BOOL (__stdcall* t_SymGetScope) (
	HANDLE       hProcess,
	ULONG64      BaseOfDll,
	DWORD        Index,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymGetScopeW) (
	HANDLE        hProcess,
	ULONG64       BaseOfDll,
	DWORD         Index,
	PSYMBOL_INFOW Symbol
	);
typedef BOOL (__stdcall* t_SymGetSearchPath) (
	HANDLE hProcess,
	PSTR   SearchPath,
	DWORD  SearchPathLength
	);
typedef BOOL (__stdcall* t_SymGetSearchPathW) (
	HANDLE hProcess,
	PWSTR  SearchPath,
	DWORD  SearchPathLength
	);
typedef BOOL (__stdcall* t_SymGetSourceFile) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCSTR   Params,
	PCSTR   FileSpec,
	PSTR    FilePath,
	DWORD   Size
	);
typedef BOOL (__stdcall* t_SymGetSourceFileChecksum) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCSTR   FileSpec,
	DWORD* pCheckSumType,
	BYTE* pChecksum,
	DWORD   checksumSize,
	DWORD* pActualBytesWritten
	);
typedef BOOL (__stdcall* t_SymGetSourceFileChecksumW) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCWSTR  FileSpec,
	DWORD* pCheckSumType,
	BYTE* pChecksum,
	DWORD   checksumSize,
	DWORD* pActualBytesWritten
	);
typedef BOOL (__stdcall* t_SymGetSourceFileFromToken) (
	HANDLE hProcess,
	PVOID  Token,
	PCSTR  Params,
	PSTR   FilePath,
	DWORD  Size
	);
typedef BOOL (__stdcall* t_SymGetSourceFileFromTokenW) (
	HANDLE hProcess,
	PVOID  Token,
	PCWSTR Params,
	PWSTR  FilePath,
	DWORD  Size
	);
typedef BOOL (__stdcall* t_SymGetSourceFileToken) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCSTR   FileSpec,
	PVOID* Token,
	DWORD* Size
	);
typedef BOOL (__stdcall* t_SymGetSourceFileTokenW) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCWSTR  FileSpec,
	PVOID* Token,
	DWORD* Size
	);
typedef BOOL (__stdcall* t_SymGetSourceFileW) (
	HANDLE  hProcess,
	ULONG64 Base,
	PCWSTR  Params,
	PCWSTR  FileSpec,
	PWSTR   FilePath,
	DWORD   Size
	);
typedef BOOL (__stdcall* t_SymGetSourceVarFromToken) (
	HANDLE hProcess,
	PVOID  Token,
	PCSTR  Params,
	PCSTR  VarName,
	PSTR   Value,
	DWORD  Size
	);
typedef BOOL (__stdcall* t_SymGetSourceVarFromTokenW) (
	HANDLE hProcess,
	PVOID  Token,
	PCWSTR Params,
	PCWSTR VarName,
	PWSTR  Value,
	DWORD  Size
	);
typedef BOOL (__stdcall* t_SymGetSymFromAddr) (
	HANDLE           hProcess,
	DWORD            dwAddr,
	PDWORD           pdwDisplacement,
	PIMAGEHLP_SYMBOL Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymFromAddr64) (
	HANDLE             hProcess,
	DWORD64            qwAddr,
	PDWORD64           pdwDisplacement,
	PIMAGEHLP_SYMBOL64 Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymFromName) (
	HANDLE           hProcess,
	PCSTR            Name,
	PIMAGEHLP_SYMBOL Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymFromName64) (
	HANDLE             hProcess,
	PCSTR              Name,
	PIMAGEHLP_SYMBOL64 Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymNext) (
	HANDLE           hProcess,
	PIMAGEHLP_SYMBOL Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymNext64) (
	HANDLE             hProcess,
	PIMAGEHLP_SYMBOL64 Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymPrev) (
	HANDLE           hProcess,
	PIMAGEHLP_SYMBOL Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymPrev64) (
	HANDLE             hProcess,
	PIMAGEHLP_SYMBOL64 Symbol
	);
typedef BOOL (__stdcall* t_SymGetSymbolFile) (
	HANDLE hProcess,
	PCSTR  SymPath,
	PCSTR  ImageFile,
	DWORD  Type,
	PSTR   SymbolFile,
	size_t cSymbolFile,
	PSTR   DbgFile,
	size_t cDbgFile
	);
typedef BOOL (__stdcall* t_SymGetSymbolFileW) (
	HANDLE hProcess,
	PCWSTR SymPath,
	PCWSTR ImageFile,
	DWORD  Type,
	PWSTR  SymbolFile,
	size_t cSymbolFile,
	PWSTR  DbgFile,
	size_t cDbgFile
	);
typedef BOOL (__stdcall* t_SymGetTypeFromName) (
	HANDLE       hProcess,
	ULONG64      BaseOfDll,
	PCSTR        Name,
	PSYMBOL_INFO Symbol
	);
typedef BOOL (__stdcall* t_SymGetTypeFromNameW) (
	HANDLE        hProcess,
	ULONG64       BaseOfDll,
	PCWSTR        Name,
	PSYMBOL_INFOW Symbol
	);
typedef BOOL (__stdcall* t_SymGetTypeInfo) (
	HANDLE                    hProcess,
	DWORD64                   ModBase,
	ULONG                     TypeId,
	IMAGEHLP_SYMBOL_TYPE_INFO GetType,
	PVOID                     pInfo
	);
typedef BOOL (__stdcall* t_SymGetTypeInfoEx) (
	HANDLE                         hProcess,
	DWORD64                        ModBase,
	PIMAGEHLP_GET_TYPE_INFO_PARAMS Params
	);
typedef BOOL (__stdcall* t_SymInitialize) (
	HANDLE hProcess,
	PCSTR  UserSearchPath,
	BOOL   fInvadeProcess
	);
typedef BOOL (__stdcall* t_SymInitializeW) (
	HANDLE hProcess,
	PCWSTR UserSearchPath,
	BOOL   fInvadeProcess
	);
typedef DWORD (__stdcall* t_SymLoadModule) (
	HANDLE hProcess,
	HANDLE hFile,
	PCSTR  ImageName,
	PCSTR  ModuleName,
	DWORD  BaseOfDll,
	DWORD  SizeOfDll
	);
typedef DWORD64 (__stdcall* t_SymLoadModule64) (
	HANDLE  hProcess,
	HANDLE  hFile,
	PCSTR   ImageName,
	PCSTR   ModuleName,
	DWORD64 BaseOfDll,
	DWORD   SizeOfDll
	);
typedef DWORD64 (__stdcall* t_SymLoadModuleEx) (
	HANDLE        hProcess,
	HANDLE        hFile,
	PCSTR         ImageName,
	PCSTR         ModuleName,
	DWORD64       BaseOfDll,
	DWORD         DllSize,
	PMODLOAD_DATA Data,
	DWORD         Flags
	);
typedef DWORD64 (__stdcall* t_SymLoadModuleExW) (
	HANDLE        hProcess,
	HANDLE        hFile,
	PCWSTR        ImageName,
	PCWSTR        ModuleName,
	DWORD64       BaseOfDll,
	DWORD         DllSize,
	PMODLOAD_DATA Data,
	DWORD         Flags
	);
typedef BOOL (__stdcall* t_SymMatchFileName) (
	PCSTR FileName,
	PCSTR Match,
	PSTR* FileNameStop,
	PSTR* MatchStop
	);
typedef BOOL (__stdcall* t_SymMatchFileNameW) (
	PCWSTR FileName,
	PCWSTR Match,
	PWSTR* FileNameStop,
	PWSTR* MatchStop
	);
typedef BOOL (__stdcall* t_SymMatchString) (
	PCSTR string,
	PCSTR expression,
	BOOL  fCase
	);
typedef BOOL (__stdcall* t_SymMatchStringA) (
	PCSTR string,
	PCSTR expression,
	BOOL  fCase
	);
typedef BOOL (__stdcall* t_SymMatchStringW) (
	PCWSTR string,
	PCWSTR expression,
	BOOL   fCase
	);
typedef BOOL (__stdcall* t_SymNext) (
	HANDLE       hProcess,
	PSYMBOL_INFO si
	);
typedef BOOL (__stdcall* t_SymNextW) (
	HANDLE        hProcess,
	PSYMBOL_INFOW siw
	);
typedef BOOL (__stdcall* t_SymPrev) (
	HANDLE       hProcess,
	PSYMBOL_INFO si
	);
typedef BOOL (__stdcall* t_SymPrevW) (
	HANDLE        hProcess,
	PSYMBOL_INFOW siw
	);
typedef BOOL (__stdcall* t_SymQueryInlineTrace) (
	HANDLE  hProcess,
	DWORD64 StartAddress,
	DWORD   StartContext,
	DWORD64 StartRetAddress,
	DWORD64 CurAddress,
	LPDWORD CurContext,
	LPDWORD CurFrameIndex
	);
typedef BOOL (__stdcall* t_SymRefreshModuleList) (
	HANDLE hProcess
	);
typedef BOOL (__stdcall* t_SymRegisterCallback) (
	HANDLE                      hProcess,
	PSYMBOL_REGISTERED_CALLBACK CallbackFunction,
	PVOID                       UserContext
	);
typedef BOOL (__stdcall* t_SymRegisterCallback64) (
	HANDLE                        hProcess,
	PSYMBOL_REGISTERED_CALLBACK64 CallbackFunction,
	ULONG64                       UserContext
	);
typedef BOOL (__stdcall* t_SymRegisterCallbackW64) (
	HANDLE                        hProcess,
	PSYMBOL_REGISTERED_CALLBACK64 CallbackFunction,
	ULONG64                       UserContext
	);
typedef BOOL (__stdcall* t_SymRegisterFunctionEntryCallback) (
	HANDLE                     hProcess,
	PSYMBOL_FUNCENTRY_CALLBACK CallbackFunction,
	PVOID                      UserContext
	);
typedef BOOL (__stdcall* t_SymRegisterFunctionEntryCallback64) (
	HANDLE                       hProcess,
	PSYMBOL_FUNCENTRY_CALLBACK64 CallbackFunction,
	ULONG64                      UserContext
	);
typedef BOOL (__stdcall* t_SymSearch) (
	HANDLE                         hProcess,
	ULONG64                        BaseOfDll,
	DWORD                          Index,
	DWORD                          SymTag,
	PCSTR                          Mask,
	DWORD64                        Address,
	PSYM_ENUMERATESYMBOLS_CALLBACK EnumSymbolsCallback,
	PVOID                          UserContext,
	DWORD                          Options
	);
typedef BOOL (__stdcall* t_SymSearchW) (
	HANDLE                          hProcess,
	ULONG64                         BaseOfDll,
	DWORD                           Index,
	DWORD                           SymTag,
	PCWSTR                          Mask,
	DWORD64                         Address,
	PSYM_ENUMERATESYMBOLS_CALLBACKW EnumSymbolsCallback,
	PVOID                           UserContext,
	DWORD                           Options
	);
typedef BOOL (__stdcall* t_SymSetContext) (
	HANDLE                hProcess,
	PIMAGEHLP_STACK_FRAME StackFrame,
	PIMAGEHLP_CONTEXT     Context
	);
typedef BOOL (__stdcall* t_SymSetExtendedOption) (
	IMAGEHLP_EXTENDED_OPTIONS option,
	BOOL                      value
	);
typedef PCHAR (__stdcall* t_SymSetHomeDirectory) (
	HANDLE hProcess,
	PCSTR  dir
	);
typedef PWSTR (__stdcall* t_SymSetHomeDirectoryW) (
	HANDLE hProcess,
	PCWSTR dir
	);
typedef DWORD (__stdcall* t_SymSetOptions) (
	DWORD SymOptions
	);
typedef BOOL (__stdcall* t_SymSetParentWindow) (
	HWND hwnd
	);
typedef BOOL (__stdcall* t_SymSetScopeFromAddr) (
	HANDLE  hProcess,
	ULONG64 Address
	);
typedef BOOL (__stdcall* t_SymSetScopeFromIndex) (
	HANDLE  hProcess,
	ULONG64 BaseOfDll,
	DWORD   Index
	);
typedef BOOL (__stdcall* t_SymSetScopeFromInlineContext) (
	HANDLE  hProcess,
	ULONG64 Address,
	ULONG   InlineContext
	);
typedef BOOL (__stdcall* t_SymSetSearchPath) (
	HANDLE hProcess,
	PCSTR  SearchPath
	);
typedef BOOL (__stdcall* t_SymSetSearchPathW) (
	HANDLE hProcess,
	PCWSTR SearchPath
	);
typedef PCSTR (__stdcall* t_SymSrvDeltaName) (
	HANDLE hProcess,
	PCSTR  SymPath,
	PCSTR  Type,
	PCSTR  File1,
	PCSTR  File2
	);
typedef PCWSTR (__stdcall* t_SymSrvDeltaNameW) (
	HANDLE hProcess,
	PCWSTR SymPath,
	PCWSTR Type,
	PCWSTR File1,
	PCWSTR File2
	);
typedef BOOL (__stdcall* t_SymSrvGetFileIndexInfo) (
	PCSTR              File,
	PSYMSRV_INDEX_INFO Info,
	DWORD              Flags
	);
typedef BOOL (__stdcall* t_SymSrvGetFileIndexInfoW) (
	PCWSTR              File,
	PSYMSRV_INDEX_INFOW Info,
	DWORD               Flags
	);
typedef BOOL (__stdcall* t_SymSrvGetFileIndexString) (
	HANDLE hProcess,
	PCSTR  SrvPath,
	PCSTR  File,
	PSTR   Index,
	size_t Size,
	DWORD  Flags
	);
typedef BOOL (__stdcall* t_SymSrvGetFileIndexStringW) (
	HANDLE hProcess,
	PCWSTR SrvPath,
	PCWSTR File,
	PWSTR  Index,
	size_t Size,
	DWORD  Flags
	);
typedef BOOL (__stdcall* t_SymSrvGetFileIndexes) (
	PCSTR  File,
	GUID* Id,
	PDWORD Val1,
	PDWORD Val2,
	DWORD  Flags
	);
typedef BOOL (__stdcall* t_SymSrvGetFileIndexesW) (
	PCWSTR File,
	GUID* Id,
	PDWORD Val1,
	PDWORD Val2,
	DWORD  Flags
	);
typedef PCSTR (__stdcall* t_SymSrvGetSupplement) (
	HANDLE hProcess,
	PCSTR  SymPath,
	PCSTR  Node,
	PCSTR  File
	);
typedef PCWSTR (__stdcall* t_SymSrvGetSupplementW) (
	HANDLE hProcess,
	PCWSTR SymPath,
	PCWSTR Node,
	PCWSTR File
	);
typedef BOOL (__stdcall* t_SymSrvIsStore) (
	HANDLE hProcess,
	PCSTR  path
	);
typedef BOOL (__stdcall* t_SymSrvIsStoreW) (
	HANDLE hProcess,
	PCWSTR path
	);
typedef PCSTR (__stdcall* t_SymSrvStoreFile) (
	HANDLE hProcess,
	PCSTR  SrvPath,
	PCSTR  File,
	DWORD  Flags
	);
typedef PCWSTR (__stdcall* t_SymSrvStoreFileW) (
	HANDLE hProcess,
	PCWSTR SrvPath,
	PCWSTR File,
	DWORD  Flags
	);
typedef PCSTR (__stdcall* t_SymSrvStoreSupplement) (
	HANDLE hProcess,
	PCSTR  SrvPath,
	PCSTR  Node,
	PCSTR  File,
	DWORD  Flags
	);
typedef PCWSTR (__stdcall* t_SymSrvStoreSupplementW) (
	HANDLE hProcess,
	PCWSTR SymPath,
	PCWSTR Node,
	PCWSTR File,
	DWORD  Flags
	);
typedef BOOL (__stdcall* t_SymUnDName) (
	PIMAGEHLP_SYMBOL sym,
	PSTR             UnDecName,
	DWORD            UnDecNameLength
	);
typedef BOOL (__stdcall* t_SymUnDName64) (
	PIMAGEHLP_SYMBOL64 sym,
	PSTR               UnDecName,
	DWORD              UnDecNameLength
	);
typedef BOOL (__stdcall* t_SymUnloadModule) (
	HANDLE hProcess,
	DWORD  BaseOfDll
	);
typedef BOOL (__stdcall* t_SymUnloadModule64) (
	HANDLE  hProcess,
	DWORD64 BaseOfDll
	);
typedef DWORD (__stdcall* t_UnDecorateSymbolName) (
	PCSTR name,
	PSTR  outputString,
	DWORD maxStringLength,
	DWORD flags
	);
typedef DWORD (__stdcall* t_UnDecorateSymbolNameW) (
	PCWSTR name,
	PWSTR  outputString,
	DWORD  maxStringLength,
	DWORD  flags
	);

// =============================================================
// Function Pointer Table
struct DebughelpApi {
	HMODULE dll_handle = NULL;

	t_EnumDirTree EnumDirTree = nullptr;
	t_EnumDirTreeW EnumDirTreeW = nullptr;
	t_EnumerateLoadedModules EnumerateLoadedModules = nullptr;
	t_EnumerateLoadedModules64 EnumerateLoadedModules64 = nullptr;
	t_EnumerateLoadedModulesEx EnumerateLoadedModulesEx = nullptr;
	t_EnumerateLoadedModulesExW EnumerateLoadedModulesExW = nullptr;
	t_EnumerateLoadedModulesW64 EnumerateLoadedModulesW64 = nullptr;
	t_FindDebugInfoFile FindDebugInfoFile = nullptr;
	t_FindDebugInfoFileEx FindDebugInfoFileEx = nullptr;
	t_FindDebugInfoFileExW FindDebugInfoFileExW = nullptr;
	t_FindExecutableImage FindExecutableImage = nullptr;
	t_FindExecutableImageEx FindExecutableImageEx = nullptr;
	t_FindExecutableImageExW FindExecutableImageExW = nullptr;
	t_GetSymLoadError GetSymLoadError = nullptr;
	t_GetTimestampForLoadedLibrary GetTimestampForLoadedLibrary = nullptr;
	t_ImageDirectoryEntryToData ImageDirectoryEntryToData = nullptr;
	t_ImageDirectoryEntryToDataEx ImageDirectoryEntryToDataEx = nullptr;
	t_ImageNtHeader ImageNtHeader = nullptr;
	t_ImageRvaToSection ImageRvaToSection = nullptr;
	t_ImageRvaToVa ImageRvaToVa = nullptr;
	t_ImagehlpApiVersion ImagehlpApiVersion = nullptr;
	t_ImagehlpApiVersionEx ImagehlpApiVersionEx = nullptr;
	t_MakeSureDirectoryPathExists MakeSureDirectoryPathExists = nullptr;
	t_MiniDumpReadDumpStream MiniDumpReadDumpStream = nullptr;
	t_MiniDumpWriteDump MiniDumpWriteDump = nullptr;
	t_SearchTreeForFile SearchTreeForFile = nullptr;
	t_SearchTreeForFileW SearchTreeForFileW = nullptr;
	t_SetSymLoadError SetSymLoadError = nullptr;
	t_StackWalk StackWalk = nullptr;
	t_StackWalk64 StackWalk64 = nullptr;
	t_StackWalkEx StackWalkEx = nullptr;
	t_SymAddSourceStream SymAddSourceStream = nullptr;
	t_SymAddSourceStreamA SymAddSourceStreamA = nullptr;
	t_SymAddSourceStreamW SymAddSourceStreamW = nullptr;
	t_SymAddSymbol SymAddSymbol = nullptr;
	t_SymAddSymbolW SymAddSymbolW = nullptr;
	t_SymAddrIncludeInlineTrace SymAddrIncludeInlineTrace = nullptr;
	t_SymCleanup SymCleanup = nullptr;
	t_SymCompareInlineTrace SymCompareInlineTrace = nullptr;
	t_SymDeleteSymbol SymDeleteSymbol = nullptr;
	t_SymDeleteSymbolW SymDeleteSymbolW = nullptr;
	t_SymEnumLines SymEnumLines = nullptr;
	t_SymEnumLinesW SymEnumLinesW = nullptr;
	t_SymEnumProcesses SymEnumProcesses = nullptr;
	t_SymEnumSourceFileTokens SymEnumSourceFileTokens = nullptr;
	t_SymEnumSourceFiles SymEnumSourceFiles = nullptr;
	t_SymEnumSourceFilesW SymEnumSourceFilesW = nullptr;
	t_SymEnumSourceLines SymEnumSourceLines = nullptr;
	t_SymEnumSourceLinesW SymEnumSourceLinesW = nullptr;
	t_SymEnumSymbols SymEnumSymbols = nullptr;
	t_SymEnumSymbolsEx SymEnumSymbolsEx = nullptr;
	t_SymEnumSymbolsExW SymEnumSymbolsExW = nullptr;
	t_SymEnumSymbolsForAddr SymEnumSymbolsForAddr = nullptr;
	t_SymEnumSymbolsForAddrW SymEnumSymbolsForAddrW = nullptr;
	t_SymEnumSymbolsW SymEnumSymbolsW = nullptr;
	t_SymEnumTypes SymEnumTypes = nullptr;
	t_SymEnumTypesByName SymEnumTypesByName = nullptr;
	t_SymEnumTypesByNameW SymEnumTypesByNameW = nullptr;
	t_SymEnumTypesW SymEnumTypesW = nullptr;
	t_SymEnumerateModules SymEnumerateModules = nullptr;
	t_SymEnumerateModules64 SymEnumerateModules64 = nullptr;
	t_SymEnumerateModulesW64 SymEnumerateModulesW64 = nullptr;
	t_SymEnumerateSymbols SymEnumerateSymbols = nullptr;
	t_SymEnumerateSymbols64 SymEnumerateSymbols64 = nullptr;
	t_SymEnumerateSymbolsW SymEnumerateSymbolsW = nullptr;
	t_SymEnumerateSymbolsW64 SymEnumerateSymbolsW64 = nullptr;
	t_SymFindDebugInfoFile SymFindDebugInfoFile = nullptr;
	t_SymFindDebugInfoFileW SymFindDebugInfoFileW = nullptr;
	t_SymFindExecutableImage SymFindExecutableImage = nullptr;
	t_SymFindExecutableImageW SymFindExecutableImageW = nullptr;
	t_SymFindFileInPath SymFindFileInPath = nullptr;
	t_SymFindFileInPathW SymFindFileInPathW = nullptr;
	t_SymFromAddr SymFromAddr = nullptr;
	t_SymFromAddrW SymFromAddrW = nullptr;
	t_SymFromIndex SymFromIndex = nullptr;
	t_SymFromIndexW SymFromIndexW = nullptr;
	t_SymFromInlineContext SymFromInlineContext = nullptr;
	t_SymFromInlineContextW SymFromInlineContextW = nullptr;
	t_SymFromName SymFromName = nullptr;
	t_SymFromNameW SymFromNameW = nullptr;
	t_SymFromToken SymFromToken = nullptr;
	t_SymFromTokenW SymFromTokenW = nullptr;
	t_SymFunctionTableAccess SymFunctionTableAccess = nullptr;
	t_SymFunctionTableAccess64 SymFunctionTableAccess64 = nullptr;
	t_SymFunctionTableAccess64AccessRoutines SymFunctionTableAccess64AccessRoutines = nullptr;
	t_SymGetExtendedOption SymGetExtendedOption = nullptr;
	t_SymGetFileLineOffsets64 SymGetFileLineOffsets64 = nullptr;
	t_SymGetHomeDirectory SymGetHomeDirectory = nullptr;
	t_SymGetHomeDirectoryW SymGetHomeDirectoryW = nullptr;
	t_SymGetLineFromAddr SymGetLineFromAddr = nullptr;
	t_SymGetLineFromAddr64 SymGetLineFromAddr64 = nullptr;
	t_SymGetLineFromAddrW64 SymGetLineFromAddrW64 = nullptr;
	t_SymGetLineFromInlineContext SymGetLineFromInlineContext = nullptr;
	t_SymGetLineFromInlineContextW SymGetLineFromInlineContextW = nullptr;
	t_SymGetLineFromName SymGetLineFromName = nullptr;
	t_SymGetLineFromName64 SymGetLineFromName64 = nullptr;
	t_SymGetLineFromNameW64 SymGetLineFromNameW64 = nullptr;
	t_SymGetLineNext SymGetLineNext = nullptr;
	t_SymGetLineNext64 SymGetLineNext64 = nullptr;
	t_SymGetLineNextW64 SymGetLineNextW64 = nullptr;
	t_SymGetLinePrev SymGetLinePrev = nullptr;
	t_SymGetLinePrev64 SymGetLinePrev64 = nullptr;
	t_SymGetLinePrevW64 SymGetLinePrevW64 = nullptr;
	t_SymGetModuleBase SymGetModuleBase = nullptr;
	t_SymGetModuleBase64 SymGetModuleBase64 = nullptr;
	t_SymGetModuleInfo SymGetModuleInfo = nullptr;
	t_SymGetModuleInfo64 SymGetModuleInfo64 = nullptr;
	t_SymGetModuleInfoW SymGetModuleInfoW = nullptr;
	t_SymGetModuleInfoW64 SymGetModuleInfoW64 = nullptr;
	t_SymGetOmaps SymGetOmaps = nullptr;
	t_SymGetOptions SymGetOptions = nullptr;
	t_SymGetScope SymGetScope = nullptr;
	t_SymGetScopeW SymGetScopeW = nullptr;
	t_SymGetSearchPath SymGetSearchPath = nullptr;
	t_SymGetSearchPathW SymGetSearchPathW = nullptr;
	t_SymGetSourceFile SymGetSourceFile = nullptr;
	t_SymGetSourceFileChecksum SymGetSourceFileChecksum = nullptr;
	t_SymGetSourceFileChecksumW SymGetSourceFileChecksumW = nullptr;
	t_SymGetSourceFileFromToken SymGetSourceFileFromToken = nullptr;
	t_SymGetSourceFileFromTokenW SymGetSourceFileFromTokenW = nullptr;
	t_SymGetSourceFileToken SymGetSourceFileToken = nullptr;
	t_SymGetSourceFileTokenW SymGetSourceFileTokenW = nullptr;
	t_SymGetSourceFileW SymGetSourceFileW = nullptr;
	t_SymGetSourceVarFromToken SymGetSourceVarFromToken = nullptr;
	t_SymGetSourceVarFromTokenW SymGetSourceVarFromTokenW = nullptr;
	t_SymGetSymFromAddr SymGetSymFromAddr = nullptr;
	t_SymGetSymFromAddr64 SymGetSymFromAddr64 = nullptr;
	t_SymGetSymFromName SymGetSymFromName = nullptr;
	t_SymGetSymFromName64 SymGetSymFromName64 = nullptr;
	t_SymGetSymNext SymGetSymNext = nullptr;
	t_SymGetSymNext64 SymGetSymNext64 = nullptr;
	t_SymGetSymPrev SymGetSymPrev = nullptr;
	t_SymGetSymPrev64 SymGetSymPrev64 = nullptr;
	t_SymGetSymbolFile SymGetSymbolFile = nullptr;
	t_SymGetSymbolFileW SymGetSymbolFileW = nullptr;
	t_SymGetTypeFromName SymGetTypeFromName = nullptr;
	t_SymGetTypeFromNameW SymGetTypeFromNameW = nullptr;
	t_SymGetTypeInfo SymGetTypeInfo = nullptr;
	t_SymGetTypeInfoEx SymGetTypeInfoEx = nullptr;
	t_SymInitialize SymInitialize = nullptr;
	t_SymInitializeW SymInitializeW = nullptr;
	t_SymLoadModule SymLoadModule = nullptr;
	t_SymLoadModule64 SymLoadModule64 = nullptr;
	t_SymLoadModuleEx SymLoadModuleEx = nullptr;
	t_SymLoadModuleExW SymLoadModuleExW = nullptr;
	t_SymMatchFileName SymMatchFileName = nullptr;
	t_SymMatchFileNameW SymMatchFileNameW = nullptr;
	t_SymMatchString SymMatchString = nullptr;
	t_SymMatchStringA SymMatchStringA = nullptr;
	t_SymMatchStringW SymMatchStringW = nullptr;
	t_SymNext SymNext = nullptr;
	t_SymNextW SymNextW = nullptr;
	t_SymPrev SymPrev = nullptr;
	t_SymPrevW SymPrevW = nullptr;
	t_SymQueryInlineTrace SymQueryInlineTrace = nullptr;
	t_SymRefreshModuleList SymRefreshModuleList = nullptr;
	t_SymRegisterCallback SymRegisterCallback = nullptr;
	t_SymRegisterCallback64 SymRegisterCallback64 = nullptr;
	t_SymRegisterCallbackW64 SymRegisterCallbackW64 = nullptr;
	t_SymRegisterFunctionEntryCallback SymRegisterFunctionEntryCallback = nullptr;
	t_SymRegisterFunctionEntryCallback64 SymRegisterFunctionEntryCallback64 = nullptr;
	t_SymSearch SymSearch = nullptr;
	t_SymSearchW SymSearchW = nullptr;
	t_SymSetContext SymSetContext = nullptr;
	t_SymSetExtendedOption SymSetExtendedOption = nullptr;
	t_SymSetHomeDirectory SymSetHomeDirectory = nullptr;
	t_SymSetHomeDirectoryW SymSetHomeDirectoryW = nullptr;
	t_SymSetOptions SymSetOptions = nullptr;
	t_SymSetParentWindow SymSetParentWindow = nullptr;
	t_SymSetScopeFromAddr SymSetScopeFromAddr = nullptr;
	t_SymSetScopeFromIndex SymSetScopeFromIndex = nullptr;
	t_SymSetScopeFromInlineContext SymSetScopeFromInlineContext = nullptr;
	t_SymSetSearchPath SymSetSearchPath = nullptr;
	t_SymSetSearchPathW SymSetSearchPathW = nullptr;
	t_SymSrvDeltaName SymSrvDeltaName = nullptr;
	t_SymSrvDeltaNameW SymSrvDeltaNameW = nullptr;
	t_SymSrvGetFileIndexInfo SymSrvGetFileIndexInfo = nullptr;
	t_SymSrvGetFileIndexInfoW SymSrvGetFileIndexInfoW = nullptr;
	t_SymSrvGetFileIndexString SymSrvGetFileIndexString = nullptr;
	t_SymSrvGetFileIndexStringW SymSrvGetFileIndexStringW = nullptr;
	t_SymSrvGetFileIndexes SymSrvGetFileIndexes = nullptr;
	t_SymSrvGetFileIndexesW SymSrvGetFileIndexesW = nullptr;
	t_SymSrvGetSupplement SymSrvGetSupplement = nullptr;
	t_SymSrvGetSupplementW SymSrvGetSupplementW = nullptr;
	t_SymSrvIsStore SymSrvIsStore = nullptr;
	t_SymSrvIsStoreW SymSrvIsStoreW = nullptr;
	t_SymSrvStoreFile SymSrvStoreFile = nullptr;
	t_SymSrvStoreFileW SymSrvStoreFileW = nullptr;
	t_SymSrvStoreSupplement SymSrvStoreSupplement = nullptr;
	t_SymSrvStoreSupplementW SymSrvStoreSupplementW = nullptr;
	t_SymUnDName SymUnDName = nullptr;
	t_SymUnDName64 SymUnDName64 = nullptr;
	t_SymUnloadModule SymUnloadModule = nullptr;
	t_SymUnloadModule64 SymUnloadModule64 = nullptr;
	t_UnDecorateSymbolName UnDecorateSymbolName = nullptr;
	t_UnDecorateSymbolNameW UnDecorateSymbolNameW = nullptr;

	~DebughelpApi () {
		unload();
	}
	void unload () {
		if (dll_handle != NULL) {
			FreeLibrary(dll_handle);
		}
		dll_handle = NULL;
	}
	bool load_if_not_loaded_yet () {
		if (dll_handle != NULL)
			return true;

		// system32
		wchar_t system_path[MAX_PATH];
		auto res = GetSystemDirectoryW(system_path, MAX_PATH);
		if (res <= 0 || res > MAX_PATH)
			return false;
		auto dbghelp_path = std::filesystem::path(system_path) / L"dbghelp.dll";

		auto dll = LoadLibraryW(dbghelp_path.c_str());
		if (dll == NULL)
			return false;

		dll_handle = dll;

		EnumDirTree = (t_EnumDirTree)GetProcAddress(dll, "EnumDirTree");
		EnumDirTreeW = (t_EnumDirTreeW)GetProcAddress(dll, "EnumDirTreeW");
		EnumerateLoadedModules = (t_EnumerateLoadedModules)GetProcAddress(dll, "EnumerateLoadedModules");
		EnumerateLoadedModules64 = (t_EnumerateLoadedModules64)GetProcAddress(dll, "EnumerateLoadedModules64");
		EnumerateLoadedModulesEx = (t_EnumerateLoadedModulesEx)GetProcAddress(dll, "EnumerateLoadedModulesEx");
		EnumerateLoadedModulesExW = (t_EnumerateLoadedModulesExW)GetProcAddress(dll, "EnumerateLoadedModulesExW");
		EnumerateLoadedModulesW64 = (t_EnumerateLoadedModulesW64)GetProcAddress(dll, "EnumerateLoadedModulesW64");
		FindDebugInfoFile = (t_FindDebugInfoFile)GetProcAddress(dll, "FindDebugInfoFile");
		FindDebugInfoFileEx = (t_FindDebugInfoFileEx)GetProcAddress(dll, "FindDebugInfoFileEx");
		FindDebugInfoFileExW = (t_FindDebugInfoFileExW)GetProcAddress(dll, "FindDebugInfoFileExW");
		FindExecutableImage = (t_FindExecutableImage)GetProcAddress(dll, "FindExecutableImage");
		FindExecutableImageEx = (t_FindExecutableImageEx)GetProcAddress(dll, "FindExecutableImageEx");
		FindExecutableImageExW = (t_FindExecutableImageExW)GetProcAddress(dll, "FindExecutableImageExW");
		GetSymLoadError = (t_GetSymLoadError)GetProcAddress(dll, "GetSymLoadError");
		GetTimestampForLoadedLibrary = (t_GetTimestampForLoadedLibrary)GetProcAddress(dll, "GetTimestampForLoadedLibrary");
		ImageDirectoryEntryToData = (t_ImageDirectoryEntryToData)GetProcAddress(dll, "ImageDirectoryEntryToData");
		ImageDirectoryEntryToDataEx = (t_ImageDirectoryEntryToDataEx)GetProcAddress(dll, "ImageDirectoryEntryToDataEx");
		ImageNtHeader = (t_ImageNtHeader)GetProcAddress(dll, "ImageNtHeader");
		ImageRvaToSection = (t_ImageRvaToSection)GetProcAddress(dll, "ImageRvaToSection");
		ImageRvaToVa = (t_ImageRvaToVa)GetProcAddress(dll, "ImageRvaToVa");
		ImagehlpApiVersion = (t_ImagehlpApiVersion)GetProcAddress(dll, "ImagehlpApiVersion");
		ImagehlpApiVersionEx = (t_ImagehlpApiVersionEx)GetProcAddress(dll, "ImagehlpApiVersionEx");
		MakeSureDirectoryPathExists = (t_MakeSureDirectoryPathExists)GetProcAddress(dll, "MakeSureDirectoryPathExists");
		MiniDumpReadDumpStream = (t_MiniDumpReadDumpStream)GetProcAddress(dll, "MiniDumpReadDumpStream");
		MiniDumpWriteDump = (t_MiniDumpWriteDump)GetProcAddress(dll, "MiniDumpWriteDump");
		SearchTreeForFile = (t_SearchTreeForFile)GetProcAddress(dll, "SearchTreeForFile");
		SearchTreeForFileW = (t_SearchTreeForFileW)GetProcAddress(dll, "SearchTreeForFileW");
		SetSymLoadError = (t_SetSymLoadError)GetProcAddress(dll, "SetSymLoadError");
		StackWalk = (t_StackWalk)GetProcAddress(dll, "StackWalk");
		StackWalk64 = (t_StackWalk64)GetProcAddress(dll, "StackWalk64");
		StackWalkEx = (t_StackWalkEx)GetProcAddress(dll, "StackWalkEx");
		SymAddSourceStream = (t_SymAddSourceStream)GetProcAddress(dll, "SymAddSourceStream");
		SymAddSourceStreamA = (t_SymAddSourceStreamA)GetProcAddress(dll, "SymAddSourceStreamA");
		SymAddSourceStreamW = (t_SymAddSourceStreamW)GetProcAddress(dll, "SymAddSourceStreamW");
		SymAddSymbol = (t_SymAddSymbol)GetProcAddress(dll, "SymAddSymbol");
		SymAddSymbolW = (t_SymAddSymbolW)GetProcAddress(dll, "SymAddSymbolW");
		SymAddrIncludeInlineTrace = (t_SymAddrIncludeInlineTrace)GetProcAddress(dll, "SymAddrIncludeInlineTrace");
		SymCleanup = (t_SymCleanup)GetProcAddress(dll, "SymCleanup");
		SymCompareInlineTrace = (t_SymCompareInlineTrace)GetProcAddress(dll, "SymCompareInlineTrace");
		SymDeleteSymbol = (t_SymDeleteSymbol)GetProcAddress(dll, "SymDeleteSymbol");
		SymDeleteSymbolW = (t_SymDeleteSymbolW)GetProcAddress(dll, "SymDeleteSymbolW");
		SymEnumLines = (t_SymEnumLines)GetProcAddress(dll, "SymEnumLines");
		SymEnumLinesW = (t_SymEnumLinesW)GetProcAddress(dll, "SymEnumLinesW");
		SymEnumProcesses = (t_SymEnumProcesses)GetProcAddress(dll, "SymEnumProcesses");
		SymEnumSourceFileTokens = (t_SymEnumSourceFileTokens)GetProcAddress(dll, "SymEnumSourceFileTokens");
		SymEnumSourceFiles = (t_SymEnumSourceFiles)GetProcAddress(dll, "SymEnumSourceFiles");
		SymEnumSourceFilesW = (t_SymEnumSourceFilesW)GetProcAddress(dll, "SymEnumSourceFilesW");
		SymEnumSourceLines = (t_SymEnumSourceLines)GetProcAddress(dll, "SymEnumSourceLines");
		SymEnumSourceLinesW = (t_SymEnumSourceLinesW)GetProcAddress(dll, "SymEnumSourceLinesW");
		SymEnumSymbols = (t_SymEnumSymbols)GetProcAddress(dll, "SymEnumSymbols");
		SymEnumSymbolsEx = (t_SymEnumSymbolsEx)GetProcAddress(dll, "SymEnumSymbolsEx");
		SymEnumSymbolsExW = (t_SymEnumSymbolsExW)GetProcAddress(dll, "SymEnumSymbolsExW");
		SymEnumSymbolsForAddr = (t_SymEnumSymbolsForAddr)GetProcAddress(dll, "SymEnumSymbolsForAddr");
		SymEnumSymbolsForAddrW = (t_SymEnumSymbolsForAddrW)GetProcAddress(dll, "SymEnumSymbolsForAddrW");
		SymEnumSymbolsW = (t_SymEnumSymbolsW)GetProcAddress(dll, "SymEnumSymbolsW");
		SymEnumTypes = (t_SymEnumTypes)GetProcAddress(dll, "SymEnumTypes");
		SymEnumTypesByName = (t_SymEnumTypesByName)GetProcAddress(dll, "SymEnumTypesByName");
		SymEnumTypesByNameW = (t_SymEnumTypesByNameW)GetProcAddress(dll, "SymEnumTypesByNameW");
		SymEnumTypesW = (t_SymEnumTypesW)GetProcAddress(dll, "SymEnumTypesW");
		SymEnumerateModules = (t_SymEnumerateModules)GetProcAddress(dll, "SymEnumerateModules");
		SymEnumerateModules64 = (t_SymEnumerateModules64)GetProcAddress(dll, "SymEnumerateModules64");
		SymEnumerateModulesW64 = (t_SymEnumerateModulesW64)GetProcAddress(dll, "SymEnumerateModulesW64");
		SymEnumerateSymbols = (t_SymEnumerateSymbols)GetProcAddress(dll, "SymEnumerateSymbols");
		SymEnumerateSymbols64 = (t_SymEnumerateSymbols64)GetProcAddress(dll, "SymEnumerateSymbols64");
		SymEnumerateSymbolsW = (t_SymEnumerateSymbolsW)GetProcAddress(dll, "SymEnumerateSymbolsW");
		SymEnumerateSymbolsW64 = (t_SymEnumerateSymbolsW64)GetProcAddress(dll, "SymEnumerateSymbolsW64");
		SymFindDebugInfoFile = (t_SymFindDebugInfoFile)GetProcAddress(dll, "SymFindDebugInfoFile");
		SymFindDebugInfoFileW = (t_SymFindDebugInfoFileW)GetProcAddress(dll, "SymFindDebugInfoFileW");
		SymFindExecutableImage = (t_SymFindExecutableImage)GetProcAddress(dll, "SymFindExecutableImage");
		SymFindExecutableImageW = (t_SymFindExecutableImageW)GetProcAddress(dll, "SymFindExecutableImageW");
		SymFindFileInPath = (t_SymFindFileInPath)GetProcAddress(dll, "SymFindFileInPath");
		SymFindFileInPathW = (t_SymFindFileInPathW)GetProcAddress(dll, "SymFindFileInPathW");
		SymFromAddr = (t_SymFromAddr)GetProcAddress(dll, "SymFromAddr");
		SymFromAddrW = (t_SymFromAddrW)GetProcAddress(dll, "SymFromAddrW");
		SymFromIndex = (t_SymFromIndex)GetProcAddress(dll, "SymFromIndex");
		SymFromIndexW = (t_SymFromIndexW)GetProcAddress(dll, "SymFromIndexW");
		SymFromInlineContext = (t_SymFromInlineContext)GetProcAddress(dll, "SymFromInlineContext");
		SymFromInlineContextW = (t_SymFromInlineContextW)GetProcAddress(dll, "SymFromInlineContextW");
		SymFromName = (t_SymFromName)GetProcAddress(dll, "SymFromName");
		SymFromNameW = (t_SymFromNameW)GetProcAddress(dll, "SymFromNameW");
		SymFromToken = (t_SymFromToken)GetProcAddress(dll, "SymFromToken");
		SymFromTokenW = (t_SymFromTokenW)GetProcAddress(dll, "SymFromTokenW");
		SymFunctionTableAccess = (t_SymFunctionTableAccess)GetProcAddress(dll, "SymFunctionTableAccess");
		SymFunctionTableAccess64 = (t_SymFunctionTableAccess64)GetProcAddress(dll, "SymFunctionTableAccess64");
		SymFunctionTableAccess64AccessRoutines = (t_SymFunctionTableAccess64AccessRoutines)GetProcAddress(dll, "SymFunctionTableAccess64AccessRoutines");
		SymGetExtendedOption = (t_SymGetExtendedOption)GetProcAddress(dll, "SymGetExtendedOption");
		SymGetFileLineOffsets64 = (t_SymGetFileLineOffsets64)GetProcAddress(dll, "SymGetFileLineOffsets64");
		SymGetHomeDirectory = (t_SymGetHomeDirectory)GetProcAddress(dll, "SymGetHomeDirectory");
		SymGetHomeDirectoryW = (t_SymGetHomeDirectoryW)GetProcAddress(dll, "SymGetHomeDirectoryW");
		SymGetLineFromAddr = (t_SymGetLineFromAddr)GetProcAddress(dll, "SymGetLineFromAddr");
		SymGetLineFromAddr64 = (t_SymGetLineFromAddr64)GetProcAddress(dll, "SymGetLineFromAddr64");
		SymGetLineFromAddrW64 = (t_SymGetLineFromAddrW64)GetProcAddress(dll, "SymGetLineFromAddrW64");
		SymGetLineFromInlineContext = (t_SymGetLineFromInlineContext)GetProcAddress(dll, "SymGetLineFromInlineContext");
		SymGetLineFromInlineContextW = (t_SymGetLineFromInlineContextW)GetProcAddress(dll, "SymGetLineFromInlineContextW");
		SymGetLineFromName = (t_SymGetLineFromName)GetProcAddress(dll, "SymGetLineFromName");
		SymGetLineFromName64 = (t_SymGetLineFromName64)GetProcAddress(dll, "SymGetLineFromName64");
		SymGetLineFromNameW64 = (t_SymGetLineFromNameW64)GetProcAddress(dll, "SymGetLineFromNameW64");
		SymGetLineNext = (t_SymGetLineNext)GetProcAddress(dll, "SymGetLineNext");
		SymGetLineNext64 = (t_SymGetLineNext64)GetProcAddress(dll, "SymGetLineNext64");
		SymGetLineNextW64 = (t_SymGetLineNextW64)GetProcAddress(dll, "SymGetLineNextW64");
		SymGetLinePrev = (t_SymGetLinePrev)GetProcAddress(dll, "SymGetLinePrev");
		SymGetLinePrev64 = (t_SymGetLinePrev64)GetProcAddress(dll, "SymGetLinePrev64");
		SymGetLinePrevW64 = (t_SymGetLinePrevW64)GetProcAddress(dll, "SymGetLinePrevW64");
		SymGetModuleBase = (t_SymGetModuleBase)GetProcAddress(dll, "SymGetModuleBase");
		SymGetModuleBase64 = (t_SymGetModuleBase64)GetProcAddress(dll, "SymGetModuleBase64");
		SymGetModuleInfo = (t_SymGetModuleInfo)GetProcAddress(dll, "SymGetModuleInfo");
		SymGetModuleInfo64 = (t_SymGetModuleInfo64)GetProcAddress(dll, "SymGetModuleInfo64");
		SymGetModuleInfoW = (t_SymGetModuleInfoW)GetProcAddress(dll, "SymGetModuleInfoW");
		SymGetModuleInfoW64 = (t_SymGetModuleInfoW64)GetProcAddress(dll, "SymGetModuleInfoW64");
		SymGetOmaps = (t_SymGetOmaps)GetProcAddress(dll, "SymGetOmaps");
		SymGetOptions = (t_SymGetOptions)GetProcAddress(dll, "SymGetOptions");
		SymGetScope = (t_SymGetScope)GetProcAddress(dll, "SymGetScope");
		SymGetScopeW = (t_SymGetScopeW)GetProcAddress(dll, "SymGetScopeW");
		SymGetSearchPath = (t_SymGetSearchPath)GetProcAddress(dll, "SymGetSearchPath");
		SymGetSearchPathW = (t_SymGetSearchPathW)GetProcAddress(dll, "SymGetSearchPathW");
		SymGetSourceFile = (t_SymGetSourceFile)GetProcAddress(dll, "SymGetSourceFile");
		SymGetSourceFileChecksum = (t_SymGetSourceFileChecksum)GetProcAddress(dll, "SymGetSourceFileChecksum");
		SymGetSourceFileChecksumW = (t_SymGetSourceFileChecksumW)GetProcAddress(dll, "SymGetSourceFileChecksumW");
		SymGetSourceFileFromToken = (t_SymGetSourceFileFromToken)GetProcAddress(dll, "SymGetSourceFileFromToken");
		SymGetSourceFileFromTokenW = (t_SymGetSourceFileFromTokenW)GetProcAddress(dll, "SymGetSourceFileFromTokenW");
		SymGetSourceFileToken = (t_SymGetSourceFileToken)GetProcAddress(dll, "SymGetSourceFileToken");
		SymGetSourceFileTokenW = (t_SymGetSourceFileTokenW)GetProcAddress(dll, "SymGetSourceFileTokenW");
		SymGetSourceFileW = (t_SymGetSourceFileW)GetProcAddress(dll, "SymGetSourceFileW");
		SymGetSourceVarFromToken = (t_SymGetSourceVarFromToken)GetProcAddress(dll, "SymGetSourceVarFromToken");
		SymGetSourceVarFromTokenW = (t_SymGetSourceVarFromTokenW)GetProcAddress(dll, "SymGetSourceVarFromTokenW");
		SymGetSymFromAddr = (t_SymGetSymFromAddr)GetProcAddress(dll, "SymGetSymFromAddr");
		SymGetSymFromAddr64 = (t_SymGetSymFromAddr64)GetProcAddress(dll, "SymGetSymFromAddr64");
		SymGetSymFromName = (t_SymGetSymFromName)GetProcAddress(dll, "SymGetSymFromName");
		SymGetSymFromName64 = (t_SymGetSymFromName64)GetProcAddress(dll, "SymGetSymFromName64");
		SymGetSymNext = (t_SymGetSymNext)GetProcAddress(dll, "SymGetSymNext");
		SymGetSymNext64 = (t_SymGetSymNext64)GetProcAddress(dll, "SymGetSymNext64");
		SymGetSymPrev = (t_SymGetSymPrev)GetProcAddress(dll, "SymGetSymPrev");
		SymGetSymPrev64 = (t_SymGetSymPrev64)GetProcAddress(dll, "SymGetSymPrev64");
		SymGetSymbolFile = (t_SymGetSymbolFile)GetProcAddress(dll, "SymGetSymbolFile");
		SymGetSymbolFileW = (t_SymGetSymbolFileW)GetProcAddress(dll, "SymGetSymbolFileW");
		SymGetTypeFromName = (t_SymGetTypeFromName)GetProcAddress(dll, "SymGetTypeFromName");
		SymGetTypeFromNameW = (t_SymGetTypeFromNameW)GetProcAddress(dll, "SymGetTypeFromNameW");
		SymGetTypeInfo = (t_SymGetTypeInfo)GetProcAddress(dll, "SymGetTypeInfo");
		SymGetTypeInfoEx = (t_SymGetTypeInfoEx)GetProcAddress(dll, "SymGetTypeInfoEx");
		SymInitialize = (t_SymInitialize)GetProcAddress(dll, "SymInitialize");
		SymInitializeW = (t_SymInitializeW)GetProcAddress(dll, "SymInitializeW");
		SymLoadModule = (t_SymLoadModule)GetProcAddress(dll, "SymLoadModule");
		SymLoadModule64 = (t_SymLoadModule64)GetProcAddress(dll, "SymLoadModule64");
		SymLoadModuleEx = (t_SymLoadModuleEx)GetProcAddress(dll, "SymLoadModuleEx");
		SymLoadModuleExW = (t_SymLoadModuleExW)GetProcAddress(dll, "SymLoadModuleExW");
		SymMatchFileName = (t_SymMatchFileName)GetProcAddress(dll, "SymMatchFileName");
		SymMatchFileNameW = (t_SymMatchFileNameW)GetProcAddress(dll, "SymMatchFileNameW");
		SymMatchString = (t_SymMatchString)GetProcAddress(dll, "SymMatchString");
		SymMatchStringA = (t_SymMatchStringA)GetProcAddress(dll, "SymMatchStringA");
		SymMatchStringW = (t_SymMatchStringW)GetProcAddress(dll, "SymMatchStringW");
		SymNext = (t_SymNext)GetProcAddress(dll, "SymNext");
		SymNextW = (t_SymNextW)GetProcAddress(dll, "SymNextW");
		SymPrev = (t_SymPrev)GetProcAddress(dll, "SymPrev");
		SymPrevW = (t_SymPrevW)GetProcAddress(dll, "SymPrevW");
		SymQueryInlineTrace = (t_SymQueryInlineTrace)GetProcAddress(dll, "SymQueryInlineTrace");
		SymRefreshModuleList = (t_SymRefreshModuleList)GetProcAddress(dll, "SymRefreshModuleList");
		SymRegisterCallback = (t_SymRegisterCallback)GetProcAddress(dll, "SymRegisterCallback");
		SymRegisterCallback64 = (t_SymRegisterCallback64)GetProcAddress(dll, "SymRegisterCallback64");
		SymRegisterCallbackW64 = (t_SymRegisterCallbackW64)GetProcAddress(dll, "SymRegisterCallbackW64");
		SymRegisterFunctionEntryCallback = (t_SymRegisterFunctionEntryCallback)GetProcAddress(dll, "SymRegisterFunctionEntryCallback");
		SymRegisterFunctionEntryCallback64 = (t_SymRegisterFunctionEntryCallback64)GetProcAddress(dll, "SymRegisterFunctionEntryCallback64");
		SymSearch = (t_SymSearch)GetProcAddress(dll, "SymSearch");
		SymSearchW = (t_SymSearchW)GetProcAddress(dll, "SymSearchW");
		SymSetContext = (t_SymSetContext)GetProcAddress(dll, "SymSetContext");
		SymSetExtendedOption = (t_SymSetExtendedOption)GetProcAddress(dll, "SymSetExtendedOption");
		SymSetHomeDirectory = (t_SymSetHomeDirectory)GetProcAddress(dll, "SymSetHomeDirectory");
		SymSetHomeDirectoryW = (t_SymSetHomeDirectoryW)GetProcAddress(dll, "SymSetHomeDirectoryW");
		SymSetOptions = (t_SymSetOptions)GetProcAddress(dll, "SymSetOptions");
		SymSetParentWindow = (t_SymSetParentWindow)GetProcAddress(dll, "SymSetParentWindow");
		SymSetScopeFromAddr = (t_SymSetScopeFromAddr)GetProcAddress(dll, "SymSetScopeFromAddr");
		SymSetScopeFromIndex = (t_SymSetScopeFromIndex)GetProcAddress(dll, "SymSetScopeFromIndex");
		SymSetScopeFromInlineContext = (t_SymSetScopeFromInlineContext)GetProcAddress(dll, "SymSetScopeFromInlineContext");
		SymSetSearchPath = (t_SymSetSearchPath)GetProcAddress(dll, "SymSetSearchPath");
		SymSetSearchPathW = (t_SymSetSearchPathW)GetProcAddress(dll, "SymSetSearchPathW");
		SymSrvDeltaName = (t_SymSrvDeltaName)GetProcAddress(dll, "SymSrvDeltaName");
		SymSrvDeltaNameW = (t_SymSrvDeltaNameW)GetProcAddress(dll, "SymSrvDeltaNameW");
		SymSrvGetFileIndexInfo = (t_SymSrvGetFileIndexInfo)GetProcAddress(dll, "SymSrvGetFileIndexInfo");
		SymSrvGetFileIndexInfoW = (t_SymSrvGetFileIndexInfoW)GetProcAddress(dll, "SymSrvGetFileIndexInfoW");
		SymSrvGetFileIndexString = (t_SymSrvGetFileIndexString)GetProcAddress(dll, "SymSrvGetFileIndexString");
		SymSrvGetFileIndexStringW = (t_SymSrvGetFileIndexStringW)GetProcAddress(dll, "SymSrvGetFileIndexStringW");
		SymSrvGetFileIndexes = (t_SymSrvGetFileIndexes)GetProcAddress(dll, "SymSrvGetFileIndexes");
		SymSrvGetFileIndexesW = (t_SymSrvGetFileIndexesW)GetProcAddress(dll, "SymSrvGetFileIndexesW");
		SymSrvGetSupplement = (t_SymSrvGetSupplement)GetProcAddress(dll, "SymSrvGetSupplement");
		SymSrvGetSupplementW = (t_SymSrvGetSupplementW)GetProcAddress(dll, "SymSrvGetSupplementW");
		SymSrvIsStore = (t_SymSrvIsStore)GetProcAddress(dll, "SymSrvIsStore");
		SymSrvIsStoreW = (t_SymSrvIsStoreW)GetProcAddress(dll, "SymSrvIsStoreW");
		SymSrvStoreFile = (t_SymSrvStoreFile)GetProcAddress(dll, "SymSrvStoreFile");
		SymSrvStoreFileW = (t_SymSrvStoreFileW)GetProcAddress(dll, "SymSrvStoreFileW");
		SymSrvStoreSupplement = (t_SymSrvStoreSupplement)GetProcAddress(dll, "SymSrvStoreSupplement");
		SymSrvStoreSupplementW = (t_SymSrvStoreSupplementW)GetProcAddress(dll, "SymSrvStoreSupplementW");
		SymUnDName = (t_SymUnDName)GetProcAddress(dll, "SymUnDName");
		SymUnDName64 = (t_SymUnDName64)GetProcAddress(dll, "SymUnDName64");
		SymUnloadModule = (t_SymUnloadModule)GetProcAddress(dll, "SymUnloadModule");
		SymUnloadModule64 = (t_SymUnloadModule64)GetProcAddress(dll, "SymUnloadModule64");
		UnDecorateSymbolName = (t_UnDecorateSymbolName)GetProcAddress(dll, "UnDecorateSymbolName");
		UnDecorateSymbolNameW = (t_UnDecorateSymbolNameW)GetProcAddress(dll, "UnDecorateSymbolNameW");

		return true;
	}
};
inline DebughelpApi real_dbghelp;
